### ISSUE TITLE
Internal GUI Improvements

### ISSUE THREAD

**Issue by dezo2** [mamedev/mame#10046]
Hello, just a few annoyances with the otherwise usable internal MAME GUI:
- Snapshot images are deformed and filtered upon each MAME restart, looking really horrible (until another ROM selection)
- Why is there a 30FPS limit? Is that for potato PC users? It makes everything so clunky and unresponsible
  -> please make an ini option for at least 60 or better yet as desktop for us snobs with 144Hz monitors
- Why is the status bar at bottom missing ROM file name?
- Also a possibility to display "Infos" tab content under the snapshot would be nice
- Searching by tiping is really weird, most of the time it just shows bunch of totally unrelated results that are not even sorted

**Comment by dezo2** [comment]
One more thing (maybe unrelated to GUI): Bitmap Prescaling in Video Options does not have any effect when "bgfx" Video Mode is selected. It works for "d3d" and "opengl" modes and I think some "bgfx" shaders could benefit from it too.

**Comment by MooglyGuy** [comment]
Hello, just a few annoyances with people who file Github issues who clearly have never been on the receiving end of a bug report, because if they did, they would do things like:
- Supply some form of screenshot to give a concrete example of these "deformed and filtered" images, rather than relying on the developers' imaginations,
- Explain what leads them to believe that there's a 30FPS limit in the UI in the first place,
- Supply a screenshot of this "status bar" and give an example of where the ROM file name should go,
- Give an example of how searching by "tiping" [sic] is "really weird", preferably with a screenshot, as well as specifying the issue in terms of expected vs. actual results rather than relying on meaningless adjectives like "weird"

**Comment by dezo2** [comment]
- Snapshot image bug and status bar request already posted in #9268, sorry I didn't search trough all issues
- I use RTSS overlay to show FPS (installed with MSI Afterburner), but it is easy observable even from mouse movement
   btw. when game is active GUI runs at the game's refresh, but the main GUI without loaded ROM is capped to 30FPS (win10)
- Regarding search just type some letters in search field and it returns list of unsorted "results" of ROM names, some of them don't even have anything in common with the search field (maybe I just don't understand the logic behind it?)

![scr_gui](https://user-images.githubusercontent.com/33813081/177660516-7ed2787e-47fd-4f92-97ba-4d53eb651e81.png)

**Comment by cuavas** [comment]
> Snapshot images are deformed and filtered upon each MAME restart, looking really horrible (until another ROM selection)

I know that – it’s moderately annoying but not close to the top of my list of priorities.  I have far bigger fish to fry.
 
> Why is there a 30FPS limit? Is that for potato PC users? It makes everything so clunky and unresponsible

The answer is rather complicated.  The 30 Hz figure arises because the system selection menu works by “emulating” an empty system and showing a menu that can’t be dismissed over the top.  For whatever reason, MAME arbitrarily sets the frame rate to 30 Hz for systems with no screens.

But the GUI doesn’t actually update at 30 Hz – because the “system” being emulated never has any screen updates and never sets any outputs, the video manager will only update every four “frames”, giving an effective rate of 7.5 Hz.  On top of that, the dodgy event handling model in the menu code means what’s displayed is one frame behind your input most of the time.  This 133 ms lag contributes more to the feeling of unresponsiveness than the low frame rate itself.

Keep in mind though that MAME always operates in immediate mode, and uses one quad per character for text.  A menu with a lot of text can tax GPU texture upload bandwidth and make your GPU heat up.  If the menus were actually being updated at 60 Hz, it wouldn’t only be a problem for “potato” PCs – it would also drain notebook batteries and spin up the fans with Intel graphics.  (You can see this in action by bringing up a heavy menu on a system that has a relatively high refresh rate.  The analog input adjustments menu on a PlayStation with a few DualShock controllers will tax your GPU.)

> Why is the status bar at bottom missing ROM file name?

Because it’s not relevant most of the time and it takes up space.  You can see the short name in the “Infos” panel.

> Also a possibility to display "Infos" tab content under the snapshot would be nice

Not worth doing without a better GUI framework with retained mode.

> Searching by tiping is really weird, most of the time it just shows bunch of totally unrelated results that are not even sorted

It uses edit distance to sort matches.  It was implemented because the previous search algorithm was worse in multiple ways (e.g. didn’t tolerate slight misspellings, performed poorly, didn’t match on short name).  If you can implement an unambiguously better search algorithm, open a pull request.

**Comment by cuavas** [comment]
> Regarding search just type some letters in search field and it returns list of unsorted "results" of ROM names, some of them don't even have anything in common with the search field (maybe I just don't understand the logic behind it?)

You don’t understand it.  For example:
* Short name for “Packri Monster” is “packmon” – edit distance of three insertions from “pacm” to “packmon”, and three-character common prefix boosts the score.
* Short name for “Panic Bomber” is “panicbom” – edit distance of four insertions from “pacm” to “panicbom”, and two-character common prefix boosts the score.
* Short name for “Space Mission (Tronica)” is “trspacmis” – edit distance of five insertions from “pacm” to “trspacmis” (“pacm” appears verbatim in the middle of of “trspacmis”).

**Comment by cuavas** [comment]
Spitballing ideas is all well and good, but the issue tracker is not the right place for it.

**Comment by dezo2** [comment]
I didn't know it is so complicated to change minor things in the GUI. As for the search - I am used to simple scrolling trough names as I type (like in other front ends), but I guess you have your reasons to implement it like this. Thanks for your time and answers.

**Comment by cuavas** [comment]
> I didn't know it is so complicated to change minor things in the GUI.

I *am* aware of many issues and limitations of the internal UI.  I’ve been working on improving it slowly.  However, the code is complicated, and there are a lot of messy dependencies, so it’s slow work.  MAME is a big project developed over decades – changing things takes time.  Things will improve, although probably not as quickly as you’d like (and definitely not as quickly as *I’d* like).
