### ISSUE TITLE
Detecting when in menu / ui.ini

### ISSUE THREAD

**Issue by ojaksch** [mamedev/mame#10099]
I have build a Marquee display bar which displays a video of the loaded game, followed by a Marquee still. This was an easy task by setting a systemd.path which is watching for _last_used_machine_ changes in _ui.ini_ and calling a simple script then.
What I'm missing when I exit back to MAME's menu is a value that _where I am now_ (=the menu).

Is there such a function/API/INI/value available?
Or, as a feature request, a new value one can use when in menu...?

**Comment by cuavas** [comment]
If by the menu, you mean when MAME is showing the system selection menu when no system is running, you can detect it because the running system has the short name `___empty` (this is due to the kind of hacky way that menu works – MAME “emulates” a system with no CPU and a 640×480 30 Hz screen that always shows black behind the menu).

**Comment by ojaksch** [comment]
This is was I also found when running `mame -verbose` and analyzing it's output, and this is working fine so far for detecting MAME's menu. Better this than nothing, but I thought that there is/will be an easier way for this.
Anyway, thanks for any support.
