### ISSUE TITLE
Possible incomplete sentence [Documentation]

### ISSUE THREAD

**Issue by cd4053** [mamedev/mame#10469]
At [Stable Controller IDs](https://docs.mamedev.org/advanced/devicemap.html) chapter, end of [Listing Available Devices](https://docs.mamedev.org/advanced/devicemap.html#listing-available-devices) the chapter ends with no conclusion.

> Note that the devices numbers in the verbose log output are zero-based, while the device numbers shown in MAME’s user interface and set in configuration files

Commit: https://github.com/mamedev/mame/commit/051c380fd14040c83a0d5b919e6289e70fef9df8

**Comment by cuavas** [comment]
Oh, that’s a bad screw-up, thanks for catching it.  The whole paragraph should have been removed, but I only removed the last line.  The logged device numbers match the device numbers in UI and configuration now.  Fixed in 7f2cbc5844515e9a54ef0646cd8f40d5e9e41a40 – it will get merged through at some point before the end of the month and appear on the web site.
