### ISSUE TITLE
lua feature request: get coords for lightgun

### ISSUE THREAD

**Issue by psakhis** [mamedev/mame#10507]
Hi,
Is it possible to know in which position (x,y) you shoot with a lightgun input dev with lua classes?

I want to reload shooting on 0,0 on some games. (opposite of offscreen_reload mame option)

Thx very much.

**Comment by cuavas** [comment]
Yes, you can read input values from the input manager, and override the values of I/O port values.
* [Input manager reference](https://docs.mamedev.org/techspecs/luareference.html#input-manager) – you can use `code_value` to read analog controls (e.g. lightgun X/Y), `code_pressed` to get the state of digital controls (e.g. buttons or keys), or `seq_pressed` to get the state of a combination of controls like MAME allows assigning to a digital input.
* [I/O port field reference](https://docs.mamedev.org/techspecs/luareference.html#i-o-port-field) – you can use `set_value` to programmatically set the value seen by the emulated machine, and `clear_value` to return it to normal behaviour.

You can look at the [autofire](https://github.com/mamedev/mame/tree/master/plugins/autofire) and [input macro](https://github.com/mamedev/mame/tree/master/plugins/inputmacro) plugins for examples of using Lua script to read user input and manipulate emulated inputs.

In the future, please use discussion forums to ask questions like this rather than opening issues.
