### ISSUE TITLE
space.debugger_access() useless and non-functional

### ISSUE THREAD

**Issue by MooglyGuy** [mamedev/mame#1089]
If I run sun4_60 with the debugger enabled, and set a breakpoint like so:

bpset ffef0004,l1==00006304

Then the following gets printed as a side effect:

https://gist.github.com/MooglyGuy/103e34b60514a55e22f93fcc2b271ebf

However, I have this as an early-out in sun4_state::timer_r

	if (space.debugger_access())
		return ret;

If you guys could fix this and then make sure someone actually competent handles debugger refactors in the future, I'd be much obliged.

**Comment by rb6502** [comment]
As discussed on Bannister, the actual problem is that bankdev doesn't pass along the debugger flag from the input address_space on its read/write handlers to the address space being called.  This also has been problematic for the Apple II, although I didn't understand why before.  So I really appreciate this report even with the aggressive phrasing :)

**Comment by rb6502** [comment]
Fixed (and verified for Ryan's example).
