### ISSUE TITLE
Well, it might not be an issue, but i found some schematics of the CPS3 board on Twitter

### ISSUE THREAD

**Issue by KNameless9999** [mamedev/mame#11149]
Maybe the CPS3 board may not be 100% accurate, but it should fix some of the issues of emulation [here](https://twitter.com/topapate/status/1620316105142312966?lang=en).

**Comment by KNameless9999** [comment]
Well, in emulation accuracy.

**Comment by Gurudumps** [comment]
Not really. That's a myth. Most modern boards are just a bunch of black custom chips with mostly unknown functions wired together. A schematic will tell you how they are wired together but it doesn't tell you the *real* signal names or the function of each pin on the custom chips or what they are actually doing. A generic reversed schematic is useless for emulation purposes. It's even useless for repair except if there's a broken trace somewhere due to damage, but that's easy to spot without a schematic. So that was basically a waste of time ;-)

**Comment by angelosa** [comment]
> Well, it might not be an issue
https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues

**Comment by DavidHaywood** [comment]
Schematics can actually be very useful, especially when trying to establish how video mixing works etc. and what is possible from a hardware point of view when trying to reverse things.  For games that rely heavily on customs, external schematics tell you a lot less, but the ones being made for the insides of individual customs can be be equally useful.

This is entirely the wrong place to be posting such things though.

**Comment by Gurudumps** [comment]
There are no public official schematics of the insides of *any* custom chips.
