### ISSUE TITLE
Vector modifications for BGFX?

### ISSUE THREAD

**Issue by Luke-Nukem** [mamedev/mame#1143]
I notice that there are [recent commits](https://github.com/mamedev/mame/commit/6ea15072a718b093e3688d22f7f6954e44e383b6) against the vector specific code.

It appears that it is geared towards Windows and DX, (am I on the right track?) is there anyone working on making it platform agnostic? Eg, Linux/OSX plus BGFX? If not, I may have a go at it, but can't promise I'll get much done due to being at university.

I don't know the MAME code base very well, so this looks like a good opportunity to do so; I just don't want to make a promise and not follow through.

**Comment by Luke-Nukem** [comment]
I'm currently digging through code and getting a feel for how such things as ```render_bounds``` work, and seeing if perhaps I could write something that renders a circle instead of a rectangle. My thinking is that if it draws a circle instead of a rectangle then there would be less need to add complexity such as smoothing the corners (in a shader for ex).

Again, I lack a deep understanding of MAME, so input and/or guidance would be great (if anyone has time).

**Comment by ImJezze** [comment]
These changes are not against the vector specific code, they are on top and part of the post processing. This is also not geared towards Windows and DirectX/HLSL. The only reason why it is not available for BGFX is that the post processing for vectors has just not been implemented yet.

I'm not a proponent of implementing vector points and rounded vector line-ends with smoothness as geometry. It would require a disproportionately high number of polygons (triangle fans or stripes with many vertices) instead of a simple rectangle (two polygons with 4 or 6 vertices) that is procedural textured. The HLSL shader could be easily adapted to BGFX, but at the moment I have no time to implement the vector post processing at first.

**Comment by Luke-Nukem** [comment]
@ImJezze thanks for the response, that clears up quite a few things for me. The link to #399 is very helpful and contains a decent amount of information to help me along.

I don't think there is anything else I need to ask for the time being so I'll close this.
