### ISSUE TITLE
Sync bx and genie with upstream

### ISSUE THREAD

**Issue by jmallach** [mamedev/mame#1144]
There are a few fixes I am interested in on both trees, and it'd make my life easier if these could be synced with MAME's 3rdparty tree.

Is that feasible for 0.176?

**Comment by mmicko** [comment]
I was away for almost all time since last release, thing is if there are
some things like ifdefs with includes for specific platform that is doable,
but can not sync all since there is a chance to broke some existing things.

if you could make pull request with minimal needed changes that could work

**Comment by jmallach** [comment]
Hi @mmicko, I can try to recompose the necessary changes into a pull request. Race against the clock though.

**Comment by jmallach** [comment]
In principle, #1147 has dealt with this.
