### ISSUE TITLE
T10MMC: Cannot install BeOS 4.5 x86 to HDD

### ISSUE THREAD

**Issue by angelosa** [mamedev/mame#11978]
Steps to reproduce:
1. Grab a BeOS 4.5 x86 distro;
2. `mamefoo pcipc -flop1 <pathto>/beos4_5.ima -cdrom <pathto>/beos4_5.cue`
3. Boot the machine, enter in Boot Options as soon as the Boot Loader switches to VGA mode by pressing space key;
4. Select new boot volume CD-ROM then Continue booting;
5. Wait until the components check fails with a CD related message. Under the hood it keeps spinning between READ TOC and READ CAPACITY.

(4)
![0263](https://github.com/mamedev/mame/assets/9251271/00054fe1-ac60-48ed-b4ca-3bd8aa328b13)

(5)
![0261](https://github.com/mamedev/mame/assets/9251271/29b9685a-e4de-4471-bb5e-11180b20de78)

**Comment by 987123879113** [comment]
This can be closed. The issue was tracked down to be a bad dumps.

- Available Aaru dump of BeOS 4.5 was dumped using a bugged version which implied there was a 2 second pregap in the first track when there wasn't (fixed in https://github.com/aaru-dps/Aaru/issues/540)
- The copy Kale was using is a single .iso which MAME sees as just a single track. BeOS 4.5 has 3 tracks and the bootloader verifies the header of all 3 tracks on boot. It can't see the other 2 tracks when using .iso so it doesn't recognize the CD.

Here's the right cue (replace bin name as appropriate):
```
FILE "beos_4_5.bin" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
  TRACK 02 MODE1/2352
    INDEX 00 04:00:00
    INDEX 01 04:02:00
  TRACK 03 MODE1/2352
    INDEX 00 38:50:34
    INDEX 01 38:52:34
```

**Comment by angelosa** [comment]
To close this I'll just consider adding a working version to the SW list, thanks for checking.

**Comment by angelosa** [comment]
https://github.com/mamedev/mame/commit/852f38865e9f19a94eb1cae0fc3e4fee9844d9fa takes care of this
