### ISSUE TITLE
Trojan detected Win.MxResIcn.Heur.Gen + suspicious behavior on 0266 windows version binaries (mame0266b_64bit.exe).

### ISSUE THREAD

**Issue by Eye-01** [mamedev/mame#12498]
### MAME version

0266

### System information

Windows 64bits

### Incorrect behaviour

Hello.
Virustotal check shows a trojan detected on mame0266b_64bit
https://www.virustotal.com/gui/file/d82402f59f2898696461bee8981cc01635b58259018d352c1402e1e042c310fc
I could consider this as false positive if there wasn't a suspicious behavior killing the windows service group WerSvcGroup and interfering with WMI :

%windir%\System32\svchost.exe -k WerSvcGroup
wmiadap.exe /F /T /R 

### Expected behaviour

should be clean on virustotal and whatever the reasons are, it shoudln't deactivate any service group or patch anything on windows system.

**Comment by cuavas** [comment]
This is a common false positive, for example see clsid2/mpc-hc#2849

Official MAME binaries do not interfere with WMI for me.  MAME uses WMI to identify the XInput controllers (based on Microsoft sample code).  If you’re treating WMI queries from applications that aren’t whitelisted as suspicious or something, you’ll get false positives.

**Comment by cuavas** [comment]
MAME does not kill any service groups.  If this is happening, it’s caused by something else on your system, not MAME.  We’d have a deluge of issue reports if this was happening.

Also, Win.MxResIcn.Heur.Gen isn’t actually identifying known malware.  It’s a heuristic.  Since around 14 June it has been causing massive numbers of false positives: https://gridinsoft.com/blogs/win-mxresicn-heur-gen-false-positive/

It’s been problematic for years – here’s a report of a false positive from 2018: https://support.mozilla.org/en-US/questions/1205467

**Comment by cuavas** [comment]
Please think about this for a second:
* The Windows Error Reporting Service is configured for Manual (Trigger Start) by default and will not be running initially.
* MAME is the first thing in the sandbox to access WMI (looking for XInput controllers), so the WMI Provider Host (wmiprvse.exe) is started on demand.
* The WMI server starts wmiadap.exe to populate objects.  This requires the Windows Error Reporting Service, causing it to start.
* When wmiadap.exe finishes populating objects, it terminates.  Since the Windows Error Reporting Service is no longer required, it is also terminated automatically.

You have not described any suspicious behaviour.

**Comment by balr0g** [comment]
Note that the report that you've linked above is for the 7-Zip self extracting archive. The 7-Zip self-extracting code, which is bundled with 7-Zip and included in self-extracting archives, may very well be calling into WMI to access the performance counters — you'd have to look at its source code.

Scanning the MAME executable itself does not show these behaviors.

**Comment by cuavas** [comment]
You’re just wasting everyone’s time.

**Comment by rb6502** [comment]
Yeah, this is ridiculous.  100% of MAME's code in a Windows build is from the source in our repo.  There's no obfuscation, nothing is touching any Windows services, and 30 other virus scanners think MAME is fine.
