### ISSUE TITLE
Compile error in mame\src\mame\exidy\circus.cpp

### ISSUE THREAD

**Issue by NEIL-smtg** [mamedev/mame#13046]
### MAME version

latest commit

### System information

Windows 11, 64-bit, version 22H2

### Incorrect behaviour

```
C:\gitP\mamedev\mame\src\mame\exidy\circus.cpp(159,46): error C2059: syntax error: ')' [C:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2022\mame_tiny.vcxproj]
C:\gitP\mamedev\mame\src\mame\exidy\circus.cpp(159,46): error C3553: decltype expects an expression not a type [C:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2022\mame_tiny.vcxproj]
C:\gitP\mamedev\mame\src\mame\exidy\circus.cpp(159,46): error C2947: expecting '>' to terminate template-argument-list, found '>' [C:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2022\mame_tiny.vcxproj]
C:\gitP\mamedev\mame\src\mame\exidy\circus.cpp(159,46): error C2440: 'static_cast': cannot convert from 'construct_ioport_circus::<lambda_8b02ac597ee9667b77f38ba7c443d7c0>' to 'ioport_value (__cdecl *)(unknown-type &)' [C:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2022\mame_tiny.vcxproj]
C:\gitP\mamedev\mame\src\mame\exidy\circus.cpp(193,47): error C2059: syntax error: ')' [C:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2022\mame_tiny.vcxproj]
C:\gitP\mamedev\mame\src\mame\exidy\circus.cpp(193,47): error C3553: decltype expects an expression not a type [C:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2022\mame_tiny.vcxproj]
C:\gitP\mamedev\mame\src\mame\exidy\circus.cpp(193,47): error C2947: expecting '>' to terminate template-argument-list, found '>' [C:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2022\mame_tiny.vcxproj]
C:\gitP\mamedev\mame\src\mame\exidy\circus.cpp(193,47): error C2440: 'static_cast': cannot convert from 'construct_ioport_robotbwl::<lambda_bbb95f7aeeb78ae8a22aff02d4a60357>' to 'ioport_value (__cdecl *)(unknown-type &)' [C:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2022\mame_tiny.vcxproj]
C:\gitP\mamedev\mame\src\mame\exidy\circus.cpp(227,47): error C2059: syntax error: ')' [C:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2022\mame_tiny.vcxproj]
C:\gitP\mamedev\mame\src\mame\exidy\circus.cpp(227,47): error C3553: decltype expects an expression not a type [C:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2022\mame_tiny.vcxproj]
C:\gitP\mamedev\mame\src\mame\exidy\circus.cpp(227,47): error C2947: expecting '>' to terminate template-argument-list, found '>' [C:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2022\mame_tiny.vcxproj]
C:\gitP\mamedev\mame\src\mame\exidy\circus.cpp(227,47): error C2440: 'static_cast': cannot convert from 'construct_ioport_crash::<lambda_9ba538c5f8b630c9eafc171cd978a745>' to 'ioport_value (__cdecl *)(unknown-type &)' [C:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2022\mame_tiny.vcxproj]
C:\gitP\mamedev\mame\src\mame\exidy\circus.cpp(267,46): error C2059: syntax error: ')' [C:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2022\mame_tiny.vcxproj]
```

### Expected behaviour

It compiles.

### Steps to reproduce

1. Open x64 native tools command prompt for vs2022
2. git clone https://github.com/mamedev/mame.git
3. cd /d C:\gitP\mamedev\mame
4. set PATH=C:\tools\msys64\usr\bin;C:\tools\msys64\mingw64\bin;%PATH% 2>&1
5. make SUBTARGET=tiny PTR64=1 TOOLS=1 OPTIMIZE=0 NOWERROR=1 MODERN_WIN_API=1 NO_USE_PORTAUDIO=1 vs2022 -j4 2>&1
6. copy C:\repos\msvc\src\qa\suites\rwc\projects\mame\projectfiles\* C:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2022
7. cd /d C:\gitP\mamedev\mame\build\projects\windows\mametiny\vs2022
8. msbuild /m /p:Platform=x64 /p:Configuration=Release /p:PreferredToolArchitecture=x64 mametiny.sln /t:Rebuild 2>&1

### Additional details

I work on Microsoft Visual C++ testing, where we regularly build popular open-source projects, including yours, with development builds of our compiler and libraries to detect and prevent shipping regressions that would affect you. This also allows us to provide advance notice of breaking changes, which is the case here.

Here is the build log: 
[mame.txt](https://github.com/user-attachments/files/18004809/mame.txt)

**Comment by angelosa** [comment]
Apparently failing at `PORT_BIT( 0x80, IP_ACTIVE_LOW, IPT_CUSTOM ) PORT_VBLANK("screen")` which are macros available in https://github.com/mamedev/mame/blob/master/src/emu/ioport.h#L1457-L1461

**Comment by pmackinlay** [comment]
Your build log appears to indicate you're not using the latest GENie and MSVC compiler options such as /Zc:preprocessor. Have you cleaned your build environment and are you working from top of tree? I think you also need to use a very recent version of MSVC delivered with VS2022 (17.12.2?).

**Comment by NEIL-smtg** [comment]
Hi @pmackinlay, the build log might suggest that I’m not using the latest released version, but my machine is actually running the latest MSVC binaries. In fact, I’m using a version that hasn’t even been officially released yet to build MAME. You can refer to this build log, which reflects the use of the latest binaries: [Build.log](https://github.com/user-attachments/files/18016599/Build.log)

**Comment by pmackinlay** [comment]
The /Zc:preprocessor and /permissive- flags don't appear to be used in your newer log file, and it also refers to a vs2019 path. Both of these may indicate your build doesn't include the changes made here dc8ba812c1099cb34f419bce0c7cc5eaf5aa3dc0, can you confirm?

**Comment by pmackinlay** [comment]
Another possible cause might be that you have not cleaned or recreated your VS build/solution files using GENie via the `make REGENIE=1` command, and therefore the new compiler options have not been specified in the build environment.

**Comment by NEIL-smtg** [comment]
I can confirm both points. I was using commit [bfb7253](https://github.com/mamedev/mame/tree/bfb7253) which is from two days ago and should include the changes in https://github.com/mamedev/mame/commit/dc8ba812c1099cb34f419bce0c7cc5eaf5aa3dc0 that you mentioned. I also tried running it with make `REGENIE=1`, but I'm still encountering the same issue."


Build log: 
[mame.txt](https://github.com/user-attachments/files/18020905/mame.txt)

**Comment by cuavas** [comment]
The macros being expanded are from src/emu/ioport.h:
```c++
// input device handler
#define PORT_READ_LINE_MEMBER_IMPL(_device, _funcptr, _name) \
    configurer.field_set_dynamic_read( \
            ioport_field_read_delegate( \
                owner, \
                _device, \`
                static_cast<ioport_value (*)(emu::detail::rw_delegate_device_class_t<decltype(_funcptr)> &)>( \
                    [] (auto &device) -> ioport_value { return (std::invoke(_funcptr, device) & 1) ? ~ioport_value(0) : 0; }), \
                _name));
#define PORT_READ_LINE_DEVICE_MEMBER(...) PORT_READ_LINE_MEMBER_IMPL(__VA_ARGS__)
#define PORT_READ_LINE_MEMBER(...) PORT_READ_LINE_MEMBER_IMPL(DEVICE_SELF, __VA_ARGS__)
```

`device` will be `"screen"`, `_funcptr` will be `&screen_device::vblank` which is an expression yielding a value of type `int (screen_device::*)()` (i.e. a member function pointer), and `_name` will be `"screen_device::vblank"`.  The thing passed to `_decltype` *is* an expression.  The compiler is misbehaving.

This report seems backwards in multiple ways:
* You’re using an internal version of the compiler that we can’t test with.  We can’t telepathically debug software that isn’t available to us.
* You seem to have jumped to blaming the input rather than entertain the possibility that your tool could be broken.
* The whole point of testing your compiler against a variety of real-world code is so that you can identify and fix issues with it, not to try and strong-arm people into pandering to your compiler’s broken behaviour.

Don’t you think your time might be better spent improving support for existing parts of the C and C++ standards, rather than trying to railroad new features into the language, like the incomprehensible coroutine features, and modules which don’t seem to actually work with real-world build tools?

**Comment by NEIL-smtg** [comment]
Hi @cuavas Thank you for your response. I understand your concerns, and I apologize if my initial report came across as accusatory or overly critical. My intent was not to assign blame but rather to identify whether the issue lies with the source code or the compiler, as it’s not immediately clear from my end.

I reported this upstream because I thought there might be value in discussing this with people more experienced in these areas. If, after your evaluation, you believe the issue is solely with the source code, I’m happy to revisit and adjust it accordingly. My goal is simply to ensure compatibility and correctness. I appreciate the time and effort you’ve put into addressing this, and I’m happy to leave it here if you feel no further action is necessary. Thanks again for your insights.

**Comment by pmackinlay** [comment]
I don't fully understand your build process, but `make SUBTARGET=tiny NOWERROR=1 vs2022 REGENIE=1 MSBUILD=1` (from an msys2 Windows Command Prompt shell with the vcvars64.bat variables set) works for me without issue. One key difference is that the standard build method does not perform your steps 6 or 7 above? Why aren't you building from the root folder, and why are you copying/overwriting the build files? Step 6 might be where you're getting incorrect build options.

The compilation failure is most certainly due to some of the compiler command line flags not being set, because I encountered these exact errors before adjusting the build configuration; specifically in this case, expanding `__VA_ARGS__` correctly requires `/Zc:preprocessor` option. Why they're not set properly in your environment is not clear to me.

**Comment by pmackinlay** [comment]
> Hi @cuavas Thank you for your response. I understand your concerns, and I apologize if my initial report came across as accusatory or overly critical. My intent was not to assign blame but rather to identify whether the issue lies with the source code or the compiler, as it’s not immediately clear from my end.

The issue is not with the source code, the issue is with the method you're using to compile it, which is not properly setting the necessary MSVC options required to make the compiler work in a mode which is sufficiently conformant to permit the code to compile. As I've mentioned already, `/utf-8`, `/Zc:preprocessor` and `/permissive-` must all be set to make it work. If you don't want to use the MAME-provided tools and configuration to build it, then you're mostly on your own, but setting those three options (at least) is still necessary.
