### ISSUE TITLE
Straighten tilted crt-geom and crt-geom-deluxe shaders

### ISSUE THREAD

**Issue by tabbycat12** [mamedev/mame#1364]
When the crt-geom shaders were imported into MAME, they were set up with a default -0.05 vertical tilt - that is, the screen is drawn so that it appears to be tilted away from the viewer at the top.

I think a better default would be to have the virtual screen drawn straight-on, with no tilt, as that gives you better use of the available physical pixels; and I think it better reflects how most users actually use MAME. Users who then want the screen tilted can either edit the config files, or save a new default from within MAME (when that's available).

It looks to me that the right spots to make the change is:
/bgfx/chains/crt-geom-deluxe.json , line 80 - change -0.05 to 0.0

/bgfx/chains/crt-geom.json , line 44 - change -0.05 to 0.0

Both of those lines appear to set the default value for MAME, as in this block of code:

    { "type": "vec2",
	  "name": "angle",
	  "text": "Tilt ",
	  "default": [ 0.0,-0.05 ],
	  "max"    : [ 1.0, 1.0 ],
	  "min"    : [-1.0,-1.0 ],
	  "step"   : 0.01,
	  "format": "%1.2f",
	  "screen": "raster" },

I've tested the change on my Windows 10 box, and it works - maybe it's something you guys could do in the source?

**Comment by u-man74** [comment]
From my experience with the CRT-geom shader and the tilt function, there are scenarios, where a 0.0 default could lead to a black screen with some graphics cards. There a threads about it at MW and we found out, that changing the tilt value to this, solved the popblem. Sadly, I cant tell which kind of setups lead to these problems, but they existed at least in the OpenGL version (the old one, not BGFX). So probably this leftover is a save default from the past. I cant speak for BGFX, maybe the problems are non existent there.

**Comment by MooglyGuy** [comment]
Thanks for the fix, tabbycat12, and thanks for the background info, u-man.

I've applied your fix as it appears to work, and credited you as [tabbycat12] in the commit log. If you'd like to be credited in some other way in the whatsnew.txt for the next version, please let me know.

I figure it's less likely to be an issue since it's BGFX handling all of the nitty-gritty OpenGL work, rather than our code. And if it does end up being an issue, then we can fix it by making the shader apply a tiny epsilon to the slider value, so that the view still looks square-on by default but the bug is still avoided.

**Comment by tabbycat12** [comment]
That's perfect, MooglyGuy, many thanks for committing the change.
