### ISSUE TITLE
Designing MAME as a secure sandbox

### ISSUE THREAD

**Issue by Sworddragon** [mamedev/mame#2378]
http://docs.mamedev.org/security.html says that MAME has not been designed/audited for security and that it had security issues in the past. There are not much details and it is hard for me to tell after reading this article how advanced MAME is in creating a secure sandboxed virtual machine, what the worst case is that could happen if arbitrary content (like BIOS ROM's and game ROM's) is being loaded (for example reading/writing directly to the hard disk, receiving/sending network data or directly executing code - all of these at the operating system level) and if all known security issues have been fixed or if there are still known ones.

I think it would be good if MAME would be designed in a way which makes it secure against such issues. If somebody wants to play old games (which probably is the main reason MAME is used) or if somebody wants to really prove the correctness of MAME documentation-wise nobody wants to have an infected system afterwards. Also if code can break out of MAME this could be/might have a negative impact on emulation accuracy.

**Comment by cuavas** [comment]
MAME is not designed as a secure sandbox.  Many trade-offs in MAME favour performance over security.  The code has not been audited.  A lot of code is not written in a secure way.  You have to assume that in the worst case, a malicious payload (e.g. a specially crafted disk image) may be able to achieve arbitrary code execution, and hence do anything the user running MAME has permission to do.

**Comment by felipesanches** [comment]
@cuavas comment is spot on!

Off course, it would be good to change that, but I'm pretty sure that the vast majority of MAME code contributors (probably 100%) are focused on dedicating their efforts towards actual emulation of systems instead of performing security audits.

Having said that, I think it is highly unlikely that anyone would oppose if a third-party contributor decided to do a security audit and submit a report, or even better, pull requests with security fixes.

**Comment by DavidHaywood** [comment]
Yeah, I wouldn't say MAME was secure in any sense.  Improvements have been made over the years because in some cases it has helped stability of drivers when the original code misbehaves - some drivers were doing horrible pointer arithmetic to the point where you had no real way to bounds check at all - but every mask you put on a memory access is an additional instruction slowing down the emulation and emulation performance can already be a significant issue.

On a related note, MAME doesn't natively provide access to the host filesystem at the moment, although it is a popular request, so might happen eventually, but doing that, by nature, is liable to introduce security risks too as you're exposing the native file system to any file infection viruses etc. that might end up being run on the emulated systems; once you go that route it actually becomes unavoidable.
