### ISSUE TITLE
coco12.cpp NitrOS9 L1 crashing on second drive access & coco3.cpp NitrOS-9 L1 crashing on second drive access.

### ISSUE THREAD

**Issue by drencorxeen** [mamedev/mame#2388]
Dear Devs,

I am having some strange crashes with both coco12.cpp & coco3.cpp areas.  Steps I was able to do to reproduce the problem.  This has been tested to work perfectly fine on REAL hardware without issues.

So DISK1 I load into disk slot 0, DISK2 I load into slot 1.  I then do DOS to boot off of DISK 1.  There is a file on DISK 2 I need to copy onto DISK1.

So I do:
copy /d1/cmds/format_20 /dd/cmds/format_20

Results on both coco3h, coco2, and coco1 as follows:

On coco3h:  NitrOS-9 copy command starts to copy the file and then the system freaks out and reboots and freezes or will display nice pretty colors and then reboots and locks up.

coco2 & coco1: copy command will start up and start copying the file and then the system just freezes.  Does nothing else, but sit there.

As I said I have verified this on both a real CoCo 3 & CoCo 2 and the exact same disk images work perfectly fine on a real systems.

**Comment by drencorxeen** [comment]
Ok so I tested more under both coco3h, coco3, coco2, coco2b, and coco1.  So when running NitrOS-9 L1 and I try to access the second disk at all more than once the system will either lockup or cause really strange activity.

So after starting up in NitrOS-9 L1 and if you type DIR /D1 and do that command a couple or so times the system goes crazy.

Now like I said I have tested this on a real CoCo. I tested using a CoCo 2 with HD63C09E CPU & CoCo3 with HD63C09E CPU.  I tested both those systems with both the CoCoSDC and two real FDC & 3.5" floppy drives.  There the same copy of NitrOS-9 L1 worked perfectly fine without any problems.

**Comment by drencorxeen** [comment]
Ok I am updating this thread as I have also been able to crash NitrOS-9 L2 on coco3 and coco3h systems which are in the coco3.cpp

I had mounted the main NitrOS-9 L2 OS boot disk in Drive0 and had KQ1 boot disk mounted in Drive 1.
After switching the working directory to /d1 and working execution directory to /d1/cmds and I started sierra the system started loading and got a boot failed screen.  I restarted MAME and tried again.

The second time I tried it the entire emulated system crashed with nice patterns on the screen.

So there is something up with the disk system when accessing the second disk drive.

And yes I have tested it on a real CoCo 3 and it works fine.  Was playing KQ1 for 2 hours on a real CoCo 3 on /d1

**Comment by drencorxeen** [comment]
I decided to make a quick video to show some quick steps to crash the emulation of the CoCo 3 environment.
https://youtu.be/5XhtqXrQ99Q

**Comment by startaq** [comment]
Can you please re-test the issues with the latest code?

I don't think the King's Quest issue is related to multiple disk drives, since even with only using one drive I get random read failures.

**Comment by drencorxeen** [comment]
@startaq ,

Currently I am in the process of testing MAME right now to make sure it is stable with the FDC stuff.

As far as the KQ1 goes in this case it wasn't KQ1 that was failing, it was because the two drives were being accessed at the same time and thus not the correct data was getting read in from the disk image.

Example of multiple things going on as a test:
[https://youtu.be/5XhtqXrQ99Q](https://youtu.be/5XhtqXrQ99Q)

Normally when I am using OS-9 L2 or NitrOS-9 L2 I am always doing multi tasking related stuff so all floppy drives would be accessed regularly.  The only reason I ran into this issue to start with is because I had just switched from another emulator to MAME at the start of June.  The reason for this change is MAME has a built in debugger which is handy.

but back to the task at hand.  Once my tests are complete I will let you know what I find.

**Comment by abcbarryn** [comment]
I applied the patch below to fix it on my copy of MAME which worked, as I understand it a different patch is being tested on the main branch. I want to recommend incorporating some of my additional comments and the fix to allow additional floppy drive types and 3 drives by default into the main code as well.

--- src/devices/bus/coco/coco_fdc.cpp	2017-08-02 01:36:40.000000000 -0400
+++ src/devices/bus/coco/coco_fdc.cpp	2017-08-02 22:13:09.000000000 -0400
@@ -118,6 +118,8 @@
 FLOPPY_FORMATS_END
 
 static SLOT_INTERFACE_START( coco_fdc_floppies )
+        SLOT_INTERFACE("ssdd", FLOPPY_525_SSDD)
+        SLOT_INTERFACE("dsdd", FLOPPY_525_DD)
 	SLOT_INTERFACE("qd", FLOPPY_525_QD)
 SLOT_INTERFACE_END
 
@@ -130,7 +132,7 @@
 	MCFG_FLOPPY_DRIVE_SOUND(true)
 	MCFG_FLOPPY_DRIVE_ADD(WD_TAG ":1", coco_fdc_floppies, "qd", coco_fdc_device_base::floppy_formats)
 	MCFG_FLOPPY_DRIVE_SOUND(true)
-	MCFG_FLOPPY_DRIVE_ADD(WD_TAG ":2", coco_fdc_floppies, nullptr, coco_fdc_device_base::floppy_formats)
+	MCFG_FLOPPY_DRIVE_ADD(WD_TAG ":2", coco_fdc_floppies, "qd", coco_fdc_device_base::floppy_formats)
 	MCFG_FLOPPY_DRIVE_SOUND(true)
 	MCFG_FLOPPY_DRIVE_ADD(WD_TAG ":3", coco_fdc_floppies, nullptr, coco_fdc_device_base::floppy_formats)
 	MCFG_FLOPPY_DRIVE_SOUND(true)
@@ -273,25 +275,32 @@
 	else if (data & 0x40)
 		drive = 3;
 
+	// Enable/disable the motor line for all drives since it is common
+	// to all drives.
 	for (int i = 0; i < 4; i++)
 	{
 		floppy_image_device *floppy = m_floppies[i]->get_device();
 		if (floppy)
-			floppy->mon_w(((i == drive) && (data & 0x08)) ? CLEAR_LINE : ASSERT_LINE);
+			floppy->mon_w((data & 0x08) ? CLEAR_LINE : ASSERT_LINE);
 	}
 
+	// Determine the value of the head (side) select line.
 	head = ((data & 0x40) && (drive != 3)) ? 1 : 0;
 
+	// Update the floppy controller register
 	set_dskreg(data);
 
 	update_lines();
 
+	// Select the floppy drive that is active.
 	floppy_image_device *selected_floppy = m_floppies[drive]->get_device();
 	m_wd17xx->set_floppy(selected_floppy);
 
+	// Apply the side select value.
 	if (selected_floppy)
 		selected_floppy->ss_w(head);
 
+	// Set the density
 	m_wd17xx->dden_w(!BIT(dskreg(), 5));
 }
 

[mame-187-floppy-patch.txt](https://github.com/mamedev/mame/files/1198071/mame-187-floppy-patch.txt)

**Comment by drencorxeen** [comment]
@startaq ,

After many hours of testing it does seem that the patch you guys pushed to the repo for coco_fdc.cpp has at least made this issue go away.

As far as your question about KQ1, the disk image I have works perfectly fine on a real FDC on a CoCo 3.
I was just giving KQ1 as one of the testing environments I was using to test/track this issue.

One of the things I did to test this issue out was on OS-9 L2 openning shells to multiple windows and then doing disk access to each floppy drive.

Example:  In Window /w5
chd /dd ; chx /dd/cmds ; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e

Example: In Window /w7
chd /d1 ; chx /d1/cmds ; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e; dir x e

Now to do this on NitrOS-9 L2 the dir command would actually be: dir -x -e

Then that would cause a extensive amount of disk activity on both drives to easily re-produce this problem on the official releases 0.163 to 0.188.

I know some people have brought up that you would be accessing more than 1 floppy at a time, but here are a few cases that you actually would do that:
Example 1:  Creating a new boot disk in /d1 with updated OS9Boot file & boot track which the os9gen utility would pool the originating files from /d0.  Then copying all the files needed for that new boot disk from /d0 to /d1.

Example 2:  copying files between disk images for specific projects.

**Comment by startaq** [comment]
Thanks, the original issue is fixed then. As for the KQ1 issue, feel free to open another issue for it, but it doesn't appear related to using two drives.
