### ISSUE TITLE
acedrvrw

### ISSUE THREAD

**Issue by zombiesbyte** [mamedev/mame#2460]
```
<input players="2" coins="2">
	<control type="joy" player="1" buttons="4" ways="vertical2"/>
	<control type="paddle" player="1" minimum="0" maximum="255" sensitivity="100" keydelta="10"/>
	<control type="pedal" player="1" minimum="0" maximum="255" sensitivity="100" keydelta="10"/>
	<control type="joy" player="2" buttons="1" ways="vertical2"/>
</input>
```
(edit, just realised the xml I've included wasn't showing so added the code tags)

Controls for this cabinet seem very strange. Firstly 4 buttons for player 1 can not be found as there seems to be only 1 change view button per player.

Secondly, player 2 controls should also have a paddle and pedal I would assume.

**Comment by happppp** [comment]
Let's see

these 2:
PORT_BIT( 0x0040, IP_ACTIVE_LOW, IPT_BUTTON3 ) PORT_NAME("View Change")
PORT_BIT( 0x8000, IP_ACTIVE_LOW, IPT_BUTTON4 ) PORT_NAME("Motion-Stop")

are 3 & 4 instead of 1 & 2 because by default button 1 & 2 are CTRL and
ALT, which are already taken by the gas pedal and brake pedal.
Motion stop is for the deluxe cabinet I guess.

And player 2? There is no user-player 2. As the PORT_NAME description says,
these controls are for service mode:
PORT_BIT( 0x0001, IP_ACTIVE_LOW, IPT_BUTTON1 ) PORT_PLAYER(2)
PORT_NAME("Dev Service Enter")
PORT_BIT( 0x0040, IP_ACTIVE_LOW, IPT_JOYSTICK_UP ) PORT_PLAYER(2)
PORT_NAME("Dev Service Up")
PORT_BIT( 0x0080, IP_ACTIVE_LOW, IPT_JOYSTICK_DOWN ) PORT_PLAYER(2)
PORT_NAME("Dev Service Down")

**Comment by happppp** [comment]
Oh, to clarify: Player 2 on the real cabinet is another PCB set. They're internally linked, this is unemulated.

**Comment by zombiesbyte** [comment]
Thanks for clarifying these points happppp. I didn't realise the 2nd player was actually a different unit which makes sense now.

I'm still a little confused why the information would still be 4 and not 2 now that you've identified the missing motion-stop button that may have only appeared on some models.

This probably isn't the place to discuss this and you clearly know more about this than I do so happy to close this issue. Thanks for looking at this.
