### ISSUE TITLE
castfant

### ISSUE THREAD

**Issue by zombiesbyte** [mamedev/mame#2471]
Astro Fantasia (DECO Cassette) (US)
manufacturer: Data East Corporation

`<input players="2" coins="2">
	<control type="joy" player="1" buttons="2" ways="8"/>
	<control type="stick" player="1" minimum="16" maximum="240" sensitivity="100" keydelta="10"/>
	<control type="joy" player="2" buttons="2" ways="8"/>
	<control type="stick" player="2" minimum="16" maximum="240" sensitivity="100" keydelta="10"/>
</input>`

From what I can determine this was a single player 2 way (left-right) 1 button CP/Rom

Thanks

**Comment by DavidHaywood** [comment]
I think you'd be better posting these to Mametesters rather than opening up an 'issue' for each one here.

In general it's a complex subject, and MAME often shows the number of buttons that a specific PCB can use, rather than the game itself.  There's currently no layer of abstraction between PCB and Cabinet when eventually there should be.

If developing your own software to run on a PCB it's important for example to know where the PCB reads all the buttons from rather than what a specific game does.

The github 'issues' I feel should be more related to actual coding problems, rather than more subjective things like this as it's the code repository.

**Comment by zombiesbyte** [comment]
Thanks David, I had no idea this was the case.

I thought I was helping, I guess all this has ended up wasting everyone's time. :(
