### ISSUE TITLE
mGBA memory tests fail on unaligned accesses

### ISSUE THREAD

**Issue by MoochMcGee** [mamedev/mame#2831]
So far only 753/1552 of these tests pass, and most of the fails appear to be due to ARM7 CPU bugs.

The test binaries can be found here: https://forums.mgba.io/showthread.php?tid=18

The lines where the problem seems to be are src/devices/cpu/arm7/arm7.cpp lines 1452, 1466, 1479, 1510, and the bit twiddling isn't even implemented in the cases handled in lines 1495 and 1500.

A working implementation can be found here: https://gitlab.com/higan/higan/blob/master/higan/processor/arm7tdmi/memory.cpp

**Comment by DopefishJustin** [comment]
Source code for the tests is at https://github.com/mgba-emu/suite/blob/master/src/memory.c

FWIW I ran this on a real GBA SP via flashcart and only 1508/1552 tests pass (the number varies a bit), the failures being in the  "ROM out-of-bounds load" section.

**Comment by MoochMcGee** [comment]
Really? Weird, according to endrift, they all pass on hardware. Then again, the suite was upped in size recently, maybe endrift forgot to update those tests.

**Comment by MoochMcGee** [comment]
Another weird occurance, not all of the tests pass in mGBA master either???

**Comment by DavidHaywood** [comment]
"ROM out-of-bounds load" differences could be because you're using a flash cart tho.. maybe it maps to areas that the regular carts don't, or accesses to certain areas have special meanings.  I'd assume it's testing for open bus behavior, mirroring or something like that (studying the source would tell us) but if your flash cart is responding in those areas it probably gets something else

I wonder how many of the tests that fail are GBA specific and how many are ARM specific.

**Comment by rb6502** [comment]
100% of the failures in mGBA's tester are GBA specific.  Unaligned access is specifically not defined by ARM.

**Comment by MoochMcGee** [comment]
@rb6502 Apparently, these tests behave the same on the DS too. Also, the GBA uses a standard ARM7TDMI, so it can't just be GBA-specific. This might affect things like the 3DO too.
@DavidHaywood Actually, I got confirmation from endrift that the ROM OOB tests are currently broken.

**Comment by balr0g** [comment]
Unaligned access is not 100% undefined: see http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.faqs/ka3772.html for details. Depending on instruction and invocation, the LSBs may be ignored entirely or rotated, or may be undefined.

https://www.heyrick.co.uk/armwiki/Unaligned_data_access also covers this.
(For reference, ARM7TDMI is ARMv4T.)

**Comment by cuavas** [comment]
Unaligned multi-word operation produce undefined behaviour on ARM.  Unaligned single word operations have defined behaviour, but it's different for different ARM versions.  The load aligned and rotate behaviour is useful for compilers emulating unaligned loads.

**Comment by cuavas** [comment]
The code to do the rotate on unaligned loads is there.  I don't know which revision your comment refers to, so I'll guess it's [fd195fdd8ab38f2d69dd82ae2fb19d55070b8e36](https://github.com/mamedev/mame/blob/fd195fdd8ab38f2d69dd82ae2fb19d55070b8e36/src/devices/cpu/arm7/arm7.cpp) since that was current when you made it.  The failing tests seem to be for 32-bit DMA and 16-bit load.  The 32-bit load tests are already passing.  Lines 1452, 1466 and 1479 are fine, and seem to be working according to the test anyway.

Unaligned 16-bit loads actually are undefined, but that aside, line 1500 doesn't need to deal with misalignment because it doesn't return immediately and gets to the check at line 1508.  Line 1510 is suspect though.

**Comment by cuavas** [comment]
Anyway, it isn't hard to fix unaligned 16-bit loads.  I can't be arsed looking at DMA and swi at the moment, but I got the passing tests up to 780 in 475cf95575c36a7bb0980f966131ebf97ecae1de
