### ISSUE TITLE
MAME .0193 + Win 10 : critical freezing issue

### ISSUE THREAD

**Issue by beatpoems** [mamedev/mame#3086]
Hello MAME-Hubsters,

I'm running version .0193 on a new Dell Inspiron laptop (core8, 8g ram), and something keeps happening
repeatedly. When I press ESC to exit a game, for example, 80% of the time the white Windows mouse cursor pops up and the game critically freezes, forcing me to force power off to reset. If I'm lucky enough to be able to alt+enter MAME into windowed mode before it crashes, it works some times for some games, but without fail crashes again. It's behaving this way in command line form as well.  Have searched high and low for a FAQ or past solution and haven't found anything - any help / suggestions would be appreciated, I'm lost here ;)

**Comment by cuavas** [comment]
This is not a help forum, it's a bug tracker.  Please use a MAME community forum for these kinds of requests:
* https://reddit.com/r/mame
* http://forum.mamedev.org/
* http://forums.bannister.org/
* http://www.mameworld.info/ubbthreads/postlist.php?Cat=&Board=mamechat

**Comment by hasen6** [comment]
He's reporting that is crashes, how in the world is that not a bug report?

**Comment by cuavas** [comment]
He hasn't given a reproducible test case or any useful information on how it's crashing, and it's not happening for other MAME users.  It's most likely a driver issue, or something else running on the system causing this.

**Comment by hasen6** [comment]
It does seem to happen a lot to other people, I'm getting crashes on loading roms, after playing for a long time or when exiting. People all seem to say it's something wrong with your computer, but it's more likely a bug or at least a combination of the MAME software and a computer problem/particular setup.

It can't be just their computer since otherwise all or most software would crash.

**Comment by MooglyGuy** [comment]
Then by all means, compile a build of MAME with symbols and get us a proper callstack for this purported crash.

Contrary to popular belief, we're not psychic, and so we need an actual call stack to work against to give even the slightest indication of what might be going wrong. We need steps to reproduce the issue on an affected machine.

What we don't need are unaffiliated, unhelpful users playing at being fucking Spartacus, demanding everything while providing absolutely nothing of substance to help in diagnosing the issue.

**Comment by hasen6** [comment]
@MooglyGuy The op probably doesn't even know what a callstack is. He's clearly tried to give a lot of information like the version, the details about his computer, that he's read the FAQ, he's described when and how the problem happened etc. Simply asking him for what you actually need would have been a lot more helpful since he's not psychic either.

Github is a programming forum and a lot of the people who post issues are also programmers...but with MAME the users are mostly just normal people. I just don't like the original response to the OP at all. If more was needed then simply asking would have been fine.

**Comment by cuavas** [comment]
As a policy, we'd prefer issues only be opened here if you have a reproducible test case.  We don't have the resources to provide individual support.  If you need help making a reproducible test case, please post on one of the MAME community forums.
