### ISSUE TITLE
DEC AlphaStation ES40 Machine Emulation Support

### ISSUE THREAD

**Issue by vincrusher** [mamedev/mame#3125]
I have an idea for a machine you could emulate, The DEC AlphaStation ES40 Computer.

Wikipedia has info about this machine at: https://en.wikipedia.org/wiki/AlphaStation#Tsunami_Family

I would think this would be a great addition to MAME.

**Comment by stilett0** [comment]
We are quite some ways away from being able to emulate that machine at any "playable" speed. We'd need a complete dynarec DEC Alpha CPU core for instance, but even that wouldn't get us to 800 MHz territory on current hardware.

Is there some reason why you mentioned this machine specifically rather than the earlier, slower models? Do you own it, for instance?

**Comment by vincrusher** [comment]
I didn't know that MAME does earlier models. I thought this would be a project to work on adding support for the Alpha CPUs. If the developers are still up for it, then that would be okay with me.

**Comment by cuavas** [comment]
Look, to put it bluntly, you're telling MAME developers to take on a large amount of work for no particular reason.  We accept external contributions.  If you're interested in adding Alpha AXP CPU emulation to MAME, we'd love to see your pull request.  If you have some application that requires emulation of these systems, you're welcome to pay someone to add the functionality to MAME, provided you honour the licenses of the other parts of MAME you link to.  However, no-one's going to jump to emulate a system like this unless they're personally interested and motivated to do it.  Opening an issue like this just comes across as demanding and inconsiderate.
