### ISSUE TITLE
Inconsistent ROM naming for SNES, other systems

### ISSUE THREAD

**Issue by zensurette** [mamedev/mame#3141]
Why are some SNES ROMs split and named after the chip in the PCB while others are single `sfc` files?

`smw2` for instance uses

    <rom name="super mario world 2 - yoshi's island (europe) (en,fr,de) (rev 1).sfc" size="2097152" crc="07e01ef9" sha1="..." offset="0x000000" />

while `smw2u` has a more sensible

    <rom name="sns-y1-1.u1" size="2097152" crc="cf98ddaa" sha1="..." offset="0x000000" />

and `srobot3rc` is totally crazy

    <dataarea name="rom" size="1572864">
        <rom name="dai-3-ji super robot taisen (japan) (rev 3).sfc" size="1572864" crc="C2941881" offset="0x000000" />
        <rom name="shvc-rt-3 p0.u1" size="1048576" crc="" sha1="" offset="0x000000" />
        <rom name="shvc-rt-3 p1.u2" size="524288"  crc="" sha1="" offset="0x100000" />
    </dataarea>

How can one help clean up this mess?

(pun intended)

**Comment by etabeta78** [comment]
On Sat, Jan 27, 2018 at 11:17 AM, zensurette <notifications@github.com>
wrote:

> Why are some SNES ROMs split and named after the chip in the PCB while
> others are single sfc files?
>
> smw2 for instance uses
>
> <rom name="super mario world 2 - yoshi's island (europe) (en,fr,de) (rev 1).sfc" size="2097152" crc="07e01ef9" sha1="..." offset="0x000000" />
>
>
Because these have not been confirmed yet, and thus we haven't had access
to the correct chip labels so to rename them accurately

while smw2u has a more sensible
>
> <rom name="sns-y1-1.u1" size="2097152" crc="cf98ddaa" sha1="..." offset="0x000000" />
>
>
all carts containing a single chip will be named like this, eventually

and srobot3rc is totally crazy
>
> <dataarea name="rom" size="1572864">
>     <rom name="dai-3-ji super robot taisen (japan) (rev 3).sfc" size="1572864" crc="C2941881" offset="0x000000" />
>     <rom name="shvc-rt-3 p0.u1" size="1048576" crc="" sha1="" offset="0x000000" />
>     <rom name="shvc-rt-3 p1.u2" size="524288"  crc="" sha1="" offset="0x100000" />
> </dataarea>
>
>
This shall be replaced by the two separate files "shvc-rt-3 p0.u1" and
"shvc-rt-3 p1.u2" as soon as we have access to an actual cart to confirm
the chip content. Since the cart contains two chips, it is correct that the
dump we document contains two separate files for the two chips...

**Comment by zensurette** [comment]
that is very clear @etabeta78!

Can you point me to a guide on how to properly dump the rommask chips? I have plenty of experience with electronics and I could contribute some proper dumps for the missing carts.
