### ISSUE TITLE
Inconsistant behaviour on wrong length and CRC

### ISSUE THREAD

**Issue by tabbycat12** [mamedev/mame#3356]
(This is going to look like a ROM request; it isn't - it's about a difference between how the GUI handles errors and how the command line does.)

I've got the wrong version of one of the SF2CE ROMS - specifically `ioc1.ic7`; and I'm running the MAME 0.195 64-bit binary on Windows 10, as downloaded from MAMEDEV.org - no mods.

If I run `mame64.exe sf2ce` from the command line, I get a warning in the GUI saying that one of the ROMs is wrong; but it's a blue (not a red) warning, it doesn't identify which ROM is wrong, and it doesn't stop me running the game. It also gives me the following (expected) error in the command prompt:
`ioc1.ic7 WRONG LENGTH (expected: 00000104 found: 00000117)
ioc1.ic7 WRONG CHECKSUMS:
    EXPECTED: CRC(a399772d) SHA1(55471189db573dd61e3087d12c55564291672c77)
       FOUND: CRC(0d182081) SHA1(475b3d417785da4bc512cce2b274bb00d4cc6792)
WARNING: the machine might not run correctly.`

If I run the same EXE by double-clicking on it, and select sf2ce, it gives me a red warning, identifies the faulty ROM, identifies that the length is wrong, and won't allow me to start the game.

Should MAME behave differently in these two cases?

**Comment by cuavas** [comment]
Yes, it's intentional. From the internal UI it checks the ROM set before launching and gives a red error message if it doesn't look correct. If at least one ROM specific you the set is present, it will also list the ROMs with issues. This avoids a lot of false bug reports and complaints that MAME doesn't tell you what's wrong.

If you launch a system directly from the command line, it's assumed you'll heed the warnings printed. This is also useful for developers testing new ROM dumps.

**Comment by ayaz1o1** [comment]
Here in the following video you can see actual and 100% easy Solution for " ioc1.ic7 (260 bytes) - INCORRECT LENGTH: 279 bytes " error ,

https://youtu.be/BfXPaIRsUHk

watch the video for easy solution for ioc1.ic7 error

if someone is facing ioc1.ic1 (260 bytes) - INCORRECT LENGTH: 279 bytes , this error usually comes in MAME Game cadillacs and dinosaurs so for Solution watch following video ,

https://youtu.be/0arxPNbLhF8
