### ISSUE TITLE
bug of "dc.xml", 2 directories are empty

### ISSUE THREAD

**Issue by newton9278** [mamedev/mame#3405]
Hello,
There is a bug of "dc.xml", these 2 directories are empty

Chaos Field (Jpn, Sega Direct) [folder: cfieldsd - parent: cfield - size: 0]
missing set: Chaos Field (Jpn, Sega Direct)

Chaos Field (Jpn, Sega Direct, Rev. 1) [folder: cfieldsd1 - parent: cfield - size: 0]
missing set: Chaos Field (Jpn, Sega Direct, Rev. 1)

Bye

**Comment by Tafoid** [comment]
This is not a bug.
The parent has the CHD needed for both of these Sega Direct sets and since the other sets have parts that are not present/not dumped (bonus CDs), it simply loads references the parent and since the names/hashes match, that is used, even if CLRMAME doesn't recognize it.  In short, you don't need a folder under the clone name because the clone has no unique content when compared to the parent at this time.

If his bothers you, visit the CLRMAME support forum.
