### ISSUE TITLE
Does MAME support UWP?

### ISSUE THREAD

**Issue by doghappy** [mamedev/mame#3452]

**Comment by DavidHaywood** [comment]
work was done on a UWP target a while back, which afaik compiled at the time, see vs2015_uwp etc. in the makefile.

I think the idea was pretty much abandoned tho, because UWP is rubbish and means, at least in certain environments, some features can't be used or don't perform efficiently due to lack of control over the system, code execution limits etc. similar to how there are limits for the in-browser solutions.  The in-browser solution was more actively maintained despite these because it's universal and the Internet Archive makes use of it.

**Comment by cuavas** [comment]
Private UWP builds could be usable, but MAME would likely never be a candidate for Windows Store. There's rudimentary support for building MAME as a UWP application, but it's effectively unmaintained. We just don't have anyone with the applicable skills and time/motivation to take it further. We'll accept patches to improve UWP support (provided they don't compromise other areas), but it's not going to be a target with mainline support any time soon.
