### ISSUE TITLE
[centronics LX810L]: SDL: ERROR! Unknown video mode: R=00000000 G=00000000 B=00000000

### ISSUE THREAD

**Issue by felipesanches** [mamedev/mame#350]
I run it this way:
./mame64 -rp ~/nonfree/MAME0164/ROMs/ at386 -board4:lpt:lpt:centronics ap2000 -window

And I get a black screen with the following error message on the text terminal being printed several times:
SDL: ERROR! Unknown video mode: R=00000000 G=00000000 B=00000000

**Comment by felipesanches** [comment]
The expected result should be something similar to this:
* https://www.youtube.com/watch?v=l20V7f2sM8c

Which is documented here:
* http://blog.arrozcru.org/?p=11
* http://blog.arrozcru.org/?p=38
* http://blog.arrozcru.org/?p=122

**Comment by rb6502** [comment]
I don't get that, but I do get the printer's status LEDs overwriting the system's main screen.  Does this work on a Windows build, because it smells like a core problem.

**Comment by rb6502** [comment]
Removing the layout fixes the problem; I get a second screen with the printer then.

**Comment by ramiropolla** [comment]
I had used a dummy centronics driver to test the printer, which can be found here:
https://github.com/ramiropolla/mame/commits/dmcntr

This dummy driver allows me to open a pipe in Linux and send data directly to MESS, which then talks directly to the printer. Basically it does 3 things:
- Opens named pipe for reading and keep it alive;
- Creates device with a high-level emulation of a centronics port for writing;
- Connects them together.

The code there is very hackish, but I'd really like to know if anyone has any suggestions on how to cleanly implement this functionality. The printer should be able to boot by itself and accept data from anywhere.

**Comment by rb6502** [comment]
Well, go ahead and comment out the MCFG line adding the artwork layout for the printer and then try the original setup Felipe was going for and see if you can get the printer to accept output from the emulated PC instead of your dummy pipe.

**Comment by ramiropolla** [comment]
Oh, yes, that worked. But for some reason I couldn't get the full printer bitmap on screen. The "printhead" never shows up on the bottom, along with the bottom lines (which should show what's currently being printed).

**Comment by awjackson** [comment]
@rb6502 requested that I clarify something: what @felipesanches is trying to do with layouts is simply not supported by the core.

MAME only supports one layout for the entire emulated machine, including all slot devices that happen to be connected. If you specify a MCFG_DEFAULT_LAYOUT in a slot device, you're overriding the layout for the entire machine, not adding elements to an existing layout. To do what he's trying to do, where you can plug a printer into a slot and have it display its own artwork and LEDs in addition to the screens and whatnot of the base system, we're going to have to come up with a whole new framework for "layout fragments" and figure out how the core should assemble them into a complete layout.

The reason slot devices with screens work is because in the absence of *any* layout file (neither user-provided, in MCFG, nor in a GAMEL macro) the core will select a default layout based (solely) on the total number of screens in the machine, including slots. But, again, this only works if there isn't any layout file. So right now, unfortunately, you can't have a machine with a built-in non-4:3 screen that also supports connecting additional screens via slots (e.g. a laptop with an external monitor port)

**Comment by mr-t-guru** [comment]
before going forward it really needs to be fixed so we can have artwork for the printer on one screen and the computer on the other screen.
also, in the youtube video above, its too fast. the printing speed needs to be set somewhere in the driver. those old printers have defined print speeds (CPS) and the demo above it going way too fast.

**Comment by rb6502** [comment]
I've seen commercial 1990s and later dot matrix printers that were as fast or faster (especially in draft mode), so it's not impossible.  But yeah, it'd be nice if @ramiropolla could verify the speeds are close to what the printer's rated for.

**Comment by mr-t-guru** [comment]
we also need some sound happening.....

**Comment by ramiropolla** [comment]
Perhaps it would be better to have the printer as a separate driver. Two instances of MAME (one for the PC, another one for the printer) communicating through some pipe or socket.

Regarding the speed, the user manual [1] says "Fast draft printing of up to 240 characters per second at 12 cpi". In the self-test there are 96 characters per line and at the fastest speed (between lines 4 and 17) it does 14 lines in around 8 seconds, which is 168 characters per second. So the speed seems about right. I don't have access to the printer anymore, but I know Felipe has an epson lx-300, which claims to be around the same (264 cps) [2]. Felipe, could you check if you get the same speed with the real printer?

Oh, and I definitely want sound. I liked the idea used by the floppy drives, but I think we could even go as far as generating sound based on the steps and the printhead firing.

[1] https://files.support.epson.com/pdf/ap2k__/ap2k__u1.pdf
[2] https://files.support.epson.com/pdf/lx300_/lx300_u1.pdf

**Comment by mr-t-guru** [comment]
I don't think we need to go as far as verifying the print speeds of actual printers. that's not practical anyway because very few people have access to the real hardware.
as long as the speed closely matches the advertised speed it will be fine.

We need a set of printer and floppy drive recording rules for key events so we can record specific sounds. At the moment very few people know exactly what sounds are needed (myself included)

**Comment by rb6502** [comment]
Bug #418 now covers this issue.
