### ISSUE TITLE
CoCo 3 driver shows both RGB and Composite screens at the same time 

### ISSUE THREAD

**Issue by tlindner** [mamedev/mame#4047]
As of MAME 0.202 the coco3 driver, by default, shows both screens side by side at the same time. I think this should be changed to show only the single Composite display by default.

**Comment by Tafoid** [comment]
You'll need to make a default layout for it.  A similar thing was needed to be done with the Sega Master System not long ago https://github.com/mamedev/mame/commit/6c74139388e8d5e4fa9db027751526cba3cf4fd3  The layouts are listed in the TAB menu -> Video Options, but the default now shows both available screens unless told otherwise.  Until then, the user simply needs to adjust the view themselves selecting Composite or RGB in the menu to make your selection.
