### ISSUE TITLE
Can't compile after updating to Ubuntu 18.10

### ISSUE THREAD

**Issue by damopinn** [mamedev/mame#4191]
I updated to ubuntu 18.10 and now I can't compile any version of mame. I tried .0202 .0201 and the latest git version. I put the last few lines of output the problems seems to be something to do with nubus but i haven't got a clue. 
 
Compiling src/devices/bus/nubus/nubus_m2video.cpp...
In file included from /usr/include/string.h:494,
                 from ../../../../../src/emu/emucore.h:19,
                 from ../../../../../src/emu/emu.h:29:
In function ‘char* strcat(char*, const char*)’,
    inlined from ‘void nubus_image_device::file_cmd_w(address_space&, offs_t, u32, u32)’ at ../../../../../src/devices/bus/nubus/nubus_image.cpp:265:10:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:128:33: error: ‘char* __builtin___strcat_chk(char*, const char*, long unsigned int)’ accessing 129 or more bytes at offsets 1028 and 900 may overlap 1 byte at offset 1028 [-Werror=restrict]
   return __builtin___strcat_chk (__dest, __src, __bos (__dest));
          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Compiling src/devices/bus/nubus/nubus_radiustpd.cpp...
Compiling src/devices/bus/nubus/nubus_spec8.cpp...
cc1plus: all warnings being treated as errors
make[2]: *** [optional.make:15228: ../../../../linux_gcc/obj/x64/Release/src/devices/bus/nubus/nubus_image.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:94: optional] Error 2
make: *** [makefile:1281: linux_x64] Error 2

**Comment by DopefishJustin** [comment]
A dev will have to check if that is a legitimate warning or not but if you add ```NOWERROR=1``` to the ```make``` command, that should get you going in the meantime. You may also need to add ```REGENIE=1``` the first time, to regenerate the makefiles.

**Comment by rb6502** [comment]
What version of GCC is this?  GCC is infamous for false errors of this type in the MAME codebase.

**Comment by damopinn** [comment]
gcc version 8.2.0 (Ubuntu 8.2.0-7ubuntu1).
Which version of gcc can I compile with?

**Comment by rb6502** [comment]
8.1.1 is known to work.

**Comment by belegdol** [comment]
Looks like the same issue as one reported over at bannister.org:
https://forums.bannister.org/ubbthreads.php?ubb=showflat&Number=114479

**Comment by cuavas** [comment]
This is caused by certain Linux distributions patching GCC to define `_FORTIFY_SOURCE` to `1` as a built-in macro, enabling additional compile- and run-time checks for certain GNU C library functions.  Gentoo and Ubuntu seem to have done this.  It's problematic for more projects than just MAME, as it makes it hard to get rid of the checks if you don't want them (e.g. if you don't want the impact of the run-time checks), and it also makes it hard to define `_FORTIFY_SOURCE` to `2` if you want to enable stricter checks.  For example you can read about the same issue on MongoDB's issue tracker [here](https://jira.mongodb.org/browse/SERVER-29982).

You should really take it up with the distribution maintainers, and make it clear you don't want them screwing up GCC.  It would be better if these distributions just defined this macro by default in the build environments for their packaging systems if they think it's important, rather than trying to force it on everything compiled on their distributions.  (This is what Red Hat does - the `_FORTIFY_SOURCE` macro is set as part of the RPM build environment, and not by shipping a modified version of GCC.)

MAME is not secure software - use it at your own risk.  We don't support building with `_FORTIFY_SOURCE` defined.  As a workaround, you can disable warnings-as-errors or add `-U_FORTIFY_SOURCE` to your compile options.
