### ISSUE TITLE
Please test more games

### ISSUE THREAD

**Issue by Jkhemili** [mamedev/mame#435]
For some odd reason, almost every game I play, it does not work. Why is This so?

**Comment by happppp** [comment]
Hi! This submit form is not for getting help to play with MAME.
I suggest you to ask on this user forum:
http://www.mameworld.info/ubbthreads/postlist.php?Cat=&Board=mamechat
(+hint: be more elaborate describing your problem to them)

**Comment by felipesanches** [comment]
@Jkhemili MAME's purpose is to preserve the history of electronic devices including, but not limited to, arcade machines, video game consoles and lots of other stuff.

The team of developers and contributors is not very big, so naturally there's lots of drivers that are still not fully implemented. In some cases the drivers are only placeholders for the purpose of preserving the ROM images so that someone can work in the future in the proper emulation of the devices.

This issue tracking system is intended to document specific known problems. Please avoid posting generic too broad requests here. A focused issue about some specific game, though, would be greatly appreciated. The olden rule is that you got to provide as much technically relevant information as possible here, so that the development team can have better conditions to tracing down the source of the issues at hand and hopefully fix them.

Happy Hacking,
Felipe "Juca" Sanches
(relatively new MAME code contributor)
