### ISSUE TITLE
Big buck hunter: bad gun mapping

### ISSUE THREAD

**Issue by legluondunet** [mamedev/mame#4447]
Hello,
I recently tested several shooting games and I found that the games Big buck hunter I and II (roms bbh2sp, bbhsc, bbh...) have a bad gun calibration.
I calibrated the game but at the end I always obtained this:

![capture d ecran de 2018-12-31 00-32-36](https://user-images.githubusercontent.com/325405/50552788-2c0ca080-0c9b-11e9-9955-03605370cce8.png)

as you can see here, the red point should be in the middle of the cross at the end of the calibration. It's the case if you stay in the middle of the screen, but not near the screen corner.
Thank you for your help.

**Comment by Tafoid** [comment]
This is already reported and logged at Mametesters!  https://mametesters.org/view.php?id=7104
Use MameTesters for posting bugs that are discovered in integer/release builds at mamedev.org

**Comment by legluondunet** [comment]
Please could you explain me why I have to report Mame bugs to two different place? 
"Use MameTesters for posting bugs that are discovered in integer/release builds at mamedev.org"
I compile git version on Ubuntu 18.04.

**Comment by MooglyGuy** [comment]
You don't have to report MAME bugs to two different places, that's the whole point of MAMETesters.

**Comment by Tafoid** [comment]
Since this is logged already, you don't need to report anything in this case.

It is expected that any issues/bugs you have that can be traced to regression between integer revision sources (published sources on mamedev.org) and that is what MameTesters.org is designed to handle.  The Git Issues should be used for reporting breakage/regression/inability to compile cutting edge Git sources when compared to the last integer source release's behavior.
