### ISSUE TITLE
unidasm crashes unexpectedly

### ISSUE THREAD

**Issue by mbates14** [mamedev/mame#4500]
Trying to disassemble a TMS34010 ROM, and no matter what I do, it crashes. 

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

Windows 7 X64, administrator command prompt. 

If I run it without the rom bin and arch, it just prints out the archs, so it at least "runs" in that regard.

**Comment by ajrhacker** [comment]
Noted and fixed in 01e459a7119a94475301d397f9c1f8b8487bb58b.

The crash was due to an incomplete implementation of address-shifted program spaces in unidasm, which called `abort()` when an architecture using the TMS34010's rightwards address-shift tried to read any length of data other than 16 bits. Unfortunately, some TMS34010 instructions have 32-bit operands.

**Comment by mbates14** [comment]
ok how do I get the exe?

**Comment by mbates14** [comment]
Hey, I think the standard MAME has the same issue. when trying to debug using the same ROM, i get all 0000s. Just like unidasm did, or crash. Your fixed worked for unidasm, but MAME itself needs fixed too.

**Comment by cuavas** [comment]
You'll need to compile the latest source yourself to get the fix, or wait for the monthly release (last Wednesday of the month - scheduled for 30 January).  We don't provide more frequent builds.

If MAME is incorrectly disassembling TMS30410 code, it would be a different issue - the code that was crashing is specific to the unidasm tool.

**Comment by Robbbert** [comment]
Is this still an issue with 0.206 ?

**Comment by Robbbert** [comment]
Nothing heard - closing.
