### ISSUE TITLE
[megadrivj] Screen is recorded off center

### ISSUE THREAD

**Issue by katananja** [mamedev/mame#4723]
`MAME v0.207 (mame0207-168-g6b67495d92)`
Windows 10 x64 1803 (17134.590)
GCC 8.2.1
Build options: `make clean && make -j5`
Run command: `mame64.exe megadrij -cart sonic -aviwrite sonic.avi`

The recorded file show the screen off center.
![sonic](https://user-images.githubusercontent.com/9029191/53839880-6d5d4d00-3f77-11e9-8ad8-c2620d87f061.png)

Snapshot and gameplay it's fine.

**Comment by Tafoid** [comment]
most video containers (AVI included) cannot change resolutions on the fly.  Megadrive/Genesis hardware frequently changes resolutions beyond what is mentioned at initialization.  While a single snapshot can keep up and is always mindful of the resolution changes, a video container cannot so you must record at the maximum expected resolution to make sure all data is captured.  In this case **-snapsize 320x224** should allow your video to be centered and completely captured.  Otherwise, you are only getting the default 256x224 setting in the video which is why you are missing the right side of the screen.

**Comment by katananja** [comment]
It's hard to keep track of all machines that switch resolutions like this.
I'll set this at `ini/source/megadrivj.ini` with a default `snapsize 320x224`.

Thank you @Tafoid 
Closed.
