### ISSUE TITLE
Add a "Mute" key for audio chip channels on the Slider Controls Menu

### ISSUE THREAD

**Issue by felipesanches** [mamedev/mame#474]
It is cumbersome to toggle on/off the sound of individual audio channels in the slider controls menu by adjusting the values from/to 0.00/1.00

It would be very handy to have a shortcut key to simply mute/unmute the currently selected channel.

**Comment by MooglyGuy** [comment]
This will be fixed in 0.172. I have just pushed a commit to the master git branch that change the controls from this:

Left/Right: Decrement/increment by internal step value
Ctrl+Left/Right: Decrement/increment by 10x internal step value
Shift+Left/Right: Decrement/increment by 0.1x internal step value

To this:

Left/Right: Decrement/increment by internal step value
Ctrl+Left/Right: Decrement/increment by 10x internal step value
Shift+Left/Right: Decrement/increment by 0.1x internal step value
Alt+Left/Right: Set slider to minimum/maximum value
Shift+Alt+Left/Right: Decrement/increment by minimum value (sometimes smaller than 'step')

**Comment by MooglyGuy** [comment]
Please let me know if this resolves your issue. If it does, please close the issue or let me know so that I can close it. Thanks!

**Comment by felipesanches** [comment]
Yeah. This sounds good (even though I have not tested it yet).
Thanks a lot for having worked on it! I appreciate it.
