### ISSUE TITLE
SDLMAME can't find system SDL2 headers

### ISSUE THREAD

**Issue by katananja** [mamedev/mame#4801]
Debian 9.6 X64
GCC 6.3.0
Build options: `make clean && make TARGETOS=windows OSD=sdl CROSS_BUILD=1`
Latest commit tested 842aa09

`-I/usr/include/SDL2` it's missing from build script.

System SDL2 files can be found with:
```
sdl2-config --libs
-L/usr/lib/x86_64-linux-gnu -lSDL2
```
And
```
sdl2-config --cflags
-I/usr/include/SDL2 -D_REENTRANT

```
```
Compiling src/osd/modules/input/input_common.cpp...
../../../../../src/osd/modules/input/input_common.cpp:36:22: fatal error: SDL2/SDL.h: No such file or directory
 #include <SDL2/SDL.h>
                      ^
compilation terminated.
osd_sdl.make:921: recipe for target '../../../../mingw-gcc/obj/x64/Release/osd_sdl/src/osd/modules/input/input_common.o' failed
make[2]: *** [../../../../mingw-gcc/obj/x64/Release/osd_sdl/src/osd/modules/input/input_common.o] Error 1
Makefile:19: recipe for target 'osd_sdl' failed
make[1]: *** [osd_sdl] Error 2
makefile:1057: recipe for target 'windows_x64' failed
make: *** [windows_x64] Error 2
```
```
make VERBOSE=1
Compiling src/osd/modules/input/input_common.cpp...
/usr/x86_64-w64-mingw32/bin/x86_64-w64-mingw32-g++    -MMD -MP -MP -DX64_WINDOWS_ABI -DPTR64=1 -DNDEBUG -DCRLF=3 -DLSB_FIRST -DFLAC__NO_DLL -DPUGIXML_HEADER_ONLY -DNATIVE_DRC=drcbe_x64 -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -DWIN32 -DUSE_NETWORK -DOSD_NET_USE_PCAP -DSDLMAME_NO_X11 -DUSE_XINPUT=0 -DSDLMAME_SDL2=1 -DOSD_SDL -DUNICODE -D_UNICODE -D_WIN32_WINNT=0x0501 -DWIN32_LEAN_AND_MEAN -DNOMINMAX -DUSE_OPENGL=1 -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -DIMGUI_DISABLE_OBSOLETE_FUNCTIONS -DUSE_QTDEBUG=0 -I"../../../../../3rdparty/asio/include" -I"../../../../../3rdparty/winpcap/Include" -I"../../../../../3rdparty/compat/mingw" -I"../../../../../3rdparty/portaudio/include" -I"../../../../../3rdparty/compat/winsdk-override" -I"../../../../../3rdparty/bgfx/examples/common" -I"../../../../../3rdparty/bgfx/include" -I"../../../../../3rdparty/bgfx/3rdparty" -I"../../../../../3rdparty/bx/include" -I"../../../../../3rdparty/rapidjson/include" -I"../../../../../3rdparty/portmidi/pm_common" -I"../../../../../src/emu" -I"../../../../../src/devices" -I"../../../../../src/osd" -I"../../../../../src/lib" -I"../../../../../src/lib/util" -I"../../../../../src/osd/modules/file" -I"../../../../../src/osd/modules/render" -I"../../../../../3rdparty" -I"../../../../../src/osd/sdl"   -g -m64 -pipe -g1 -fno-omit-frame-pointer -fno-optimize-sibling-calls -O3 -fno-strict-aliasing -march="bdver1" -mfpmath=sse -Wno-unknown-pragmas -Wall -Wcast-align -Wundef -Wformat-security -Wwrite-strings -Wno-sign-compare -Wno-conversion -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -m64 -x c++ -std=c++14 -Woverloaded-virtual -include /home/mame/build/mame/src/osd/sdl/sdlprefix.h -o "../../../../mingw-gcc/obj/x64/Release/osd_sdl/src/osd/modules/input/input_common.o" -c "../../../../../src/osd/modules/input/input_common.cpp"
../../../../../src/osd/modules/input/input_common.cpp:36:22: fatal error: SDL2/SDL.h: No such file or directory
 #include <SDL2/SDL.h>
                      ^
compilation terminated.
osd_sdl.make:921: recipe for target '../../../../mingw-gcc/obj/x64/Release/osd_sdl/src/osd/modules/input/input_common.o' failed
make[2]: *** [../../../../mingw-gcc/obj/x64/Release/osd_sdl/src/osd/modules/input/input_common.o] Error 1
Makefile:19: recipe for target 'osd_sdl' failed
make[1]: *** [osd_sdl] Error 2
make[1]: Leaving directory '/home/mame/build/mame/build/projects/sdl/mametiny/gmake-mingw64-gcc'
makefile:1057: recipe for target 'windows_x64' failed
make: *** [windows_x64] Error 2
```

**Comment by cuavas** [comment]
This is not necessary on Fedora - the library headers are found correctly.  Use `ARCHOPTS` or figure out why the mingw paths aren't being used by default.

**Comment by katananja** [comment]
I didn't file a bug for Fedora, people are aware that Fedora it's a unstable system and it is a test bed for RHEL. Anyway, this is not about Fedora.

The way the build scripts are made it should be smart enough to detect what it needs from the system by it self without the need for `ARCHOPTS` since there are tools available to use and depending on the system `sdl2-config` should return the proper paths for libs and includes.

The reason MAME fail to build it's because the build scripts uses a nasty hack like this one that replaces `/SDL2` with nothing:
`backtick(sdlconfigcmd() .. " --cflags | sed 's:/SDL2::'")`

If you run it on mingw for instance:
`sdl2-config --cflags | sed 's:SDL2::'`

It return:
`-I/mingw64/include/ -Dmain=SDL_main`

The correct path for SDL2 headers is:
```
sdl2-config --cflags
-I/mingw64/include/SDL2 -Dmain=SDL_main
```
Same happens on Linux, the build script uses `-I/usr/include` instead of `-I/usr/include/SDL2` and it will obviously fail to compile either on Linux or mingw.

The second reason why this is failing it's because there are no proper conditionals for `targetos == windows`, if we take example from `targetos == macosx`:
```
if BASE_TARGETOS=="unix" then
	defines {
		"SDLMAME_UNIX",
	}
	if _OPTIONS["targetos"]=="macosx" then
		if _OPTIONS["with-bundled-sdl2"]==nil then
			if _OPTIONS["USE_LIBSDL"]~="1" then
				buildoptions {
					"-F" .. _OPTIONS["SDL_FRAMEWORK_PATH"],
				}
			else
				defines {
					"MACOSX_USE_LIBSDL",
				}
				buildoptions {
					backtick(sdlconfigcmd() .. " --cflags | sed 's:/SDL2::'"),
				}
			end
		end
	else
		buildoptions {
			backtick(sdlconfigcmd() .. " --cflags"),
		}
		if _OPTIONS["targetos"]~="asmjs" then
			buildoptions {
				backtick(pkgconfigcmd() .. " --cflags fontconfig"),
			}
		end
	end
end
```
We can see `buildoptions` getting the SDL2 **path hack**, now if we look in to `targetos == windows`:
```
if _OPTIONS["targetos"]=="windows" then
	configuration { "mingw* or vs*" }
		defines {
			"UNICODE",
			"_UNICODE",
			"_WIN32_WINNT=0x0501",
			"WIN32_LEAN_AND_MEAN",
			"NOMINMAX",
		}

	configuration { }
```
This is basically it, we can't see any SDL2 configuration on either `sdl.lua` or `sdl_cfg.lua` for `targetos == windows` and still don't understand why it passes `-I/mingw64/include/` to the compiler since this is defined for `macosx`.

I didn't test at the time for lack of time, the regression is this 8ffff5d2d3bcebbdbefec2508ddd2ecd264a399a, removing `ifneq '$(USE_BUNDLED_LIB_SDL2)' '0'` and `endif` from the makefile and building with `USE_BUNDLED_LIB_SDL2=0` for some kind of miracle this make it work again. And when I say "_miracle_" it's because there is nothing on the script passing the correct path for the compiler but still it compiles all the way through because even set as `0` it uses the bundled SDL2 from MAME when it should use the system.

Do you concur?

**Comment by cuavas** [comment]
Fedora is "unstable" in the sense that it's updated relatively quickly and packaged software occasionally gets a major version upgrade before a distribution update.  It isn't "unstable" in the sense of crashing or not working.  Being the "testbed for RHEL" is exactly why a lot of people use it.  It uses the same packaging system, similar network and service configuration, it's largely ABI-compatible (e.g. it uses the same versioning for FIPS-compliant OpenSSL), and it gives you a preview of where RHEL/CentOS may be going.  The benefits are huge for people who, like me, use RHEL for deployment of line-of-business applications.

You're misunderstanding why it does special stuff for macOS - on macOS a system installation of SDL2 uses a NeXT-style framework, which is not used for any other target.

Before 8ffff5d2d3bcebbdbefec2508ddd2ecd264a399a `USE_BUNDLED_LIB_SDL2=0` and `USE_BUNDLED_LIB_SDL2=1` did the same thing.  The option wasn't working intuitively.  It's not a regression that `0` now disables the option instead of doing the same thing as `1`.

Stripping `/SDL2` from the end of the include path is intentional.  For consistency between macOS and other platforms, MAME includes the `SDL2/` prefix when including SDL2 headers.  Hence, the parent directory is what we need to add to the include path.

Your analysis is completely flawed, and the issue you're reporting is not happening for others.

**Comment by cuavas** [comment]
@katananja between this and #4789 you've shown that you don't seem to have learned anything about how now to use the issue tracker, and how not to get developers off-side.  You're getting a 6-week ban for this.

**Comment by wtuemura** [comment]
This is not the real reason your are giving a ban, it's to hide your own incompetence [again](https://github.com/mamedev/mame/issues/2874), and [again](https://github.com/mamedev/mame/issues/4661) and we can go on and on, how many times you are gonna close legit reports to dealt with it later?

This is what happens when you give a nobody like you some power, they like to show off and oppress other people, to shut people off, **you are disgusting and a coward**. What you are gonna do now? Delete messages like you did before?

It doesn't matter the lame excuse you've gave, it doesn't change the fact that the script it's passing the wrong path to the compiler and #4789 it's breaking MAME memory space . And don't get me wrong, I know how to use a issue tracker, in an organize project, the issue it's acknowledge, tagged and dealt with latter.

If you or any other dev will handle it now, tomorrow or 10 years from now, **I don't care**. It's a damn bug report and not a help request. Why all the drama about it, what are you afraid of?

Respect it's a thing we earn, you give respect you shall receive it, if you come towards me in a disrespectful manner I'll shake you off my way and I don't care if you are a fruit cake or a snow flake or whatever generation name you people call yourself this days.

Don't expect me to respect a sick, mental ill and suicidal person like @MooglyGuy that like to attack and persecute people for unknown reason.
https://i.postimg.cc/h45x3G92/Moogly-Guy.png

This is the kind of person you give authority to and allow him to take on other people.

**Comment by cuavas** [comment]
@wtuemura ban evasion is abuse, and will be reported.

**Comment by wtuemura** [comment]
I'll report you too @cuavas, for all the internet to see how disgusting and abusive you are.
`#mamegate`
