### ISSUE TITLE
Minor CPS-1 inaccuracy (Daimakaimura loading times)

### ISSUE THREAD

**Issue by oranki** [mamedev/mame#5057]
In Daimakaimura (Ghouls'n Ghosts), each loading screen between stages/cutscenes is roughly 8 frames shorter than on PCB.

Disclaimer: I'm not expecting this to be taken very seriously, since it affects absolutely nobody except for a handful of speedrunners. Just wanted to let you know, in case it might be helpful for further improving the CPS-1 emulation accuracy.

**Comment by oranki** [comment]
I apologise for earlier misinformed bug report. I checked a few other recordings and it seems on original PCB, the loading time difference between board and emu is only 4~5 frames, my scrub conversion board just has additional loading time.

**Comment by rb6502** [comment]
This is the same issue as SSF2 being too fast or whatever.  Lack of wait states.

**Comment by angelosa** [comment]
Or sprite chip delays (cfr. Strider with stage 4 dinosaurs is supposed to run like [this](https://youtu.be/RIBy49CKMmY?t=2447) ) 
Known as MAMEtesters [00408](https://mametesters.org/view.php?id=408) and [01989](https://mametesters.org/view.php?id=1989) and [07443](https://mametesters.org/view.php?id=7443) at very least.
I'm not sure about keeping this open since we already have enough proof and reports.

**Comment by zaphod77** [comment]
A

> This is the same issue as SSF2 being too fast or whatever. Lack of wait states. Nobody emulates this correctly yet, it's an annoying problem.

Actually, Callus seems to get this correct _somehow_ in every game it supports, according to the internet and many hyper fighting fans, but no one knows how Sardu did it and he's not telling.

Note that Callus supports this game, so please test if you can. :)
