### ISSUE TITLE
MAME 0.210 -verifyroms shows info not just related to "roms" folder

### ISSUE THREAD

**Issue by mackonsti** [mamedev/mame#5232]
Hi everyone and many thanks for your great work! I have installed the latest MAME v0.210 (on Windows 10) and when populating the "roms" folder with some items to validate, I run with -verifyroms without a ROM name and get a list of ROMs that have nothing to do with the folder contents.

The CMD line **MAME64.exe -verifyroms {rom.zip}** works fine. But if I want to validate all "roms" folder contents, I run simply **MAME64.exe -verifyroms** and get a list of other stuff that I have no idea where they come from. The "roms" items _are shown_ in that long list, but the problem is that if I do **MAME64.exe -verifyroms >> list.txt** I get much more than my handful of ROMs. I believe it counts some internal stuff?

I have cleanly installed it 3 times, same results.
Please let me know what info/log you'd like me to provide more. Thanks again!

**Comment by Tafoid** [comment]
The UI, by default, filters these "romless" machines that you have immediate access to when starting MAME and therefore will not list them under "Available".  Through -verifyroms, there is no such filter and shows all machines which pass an audit.  Since these romless (or no good dump known) machines will all show as Best Available, they are listed as available machines to you.   You can see a list of these by starting your UI and going to CONFIGURE OPTIONS->MISCELLANEOUS OPTIONS-> "Hide romless machine from available list" to OFF when pointing to an empty rompath.

As far as I know, there is no option to hide such machines from -verifyroms, however.  You can filter them by ignoring "Best Available" results with NO GOOD DUMP KNOWN parts, I reckon,  Alternatively, you can check for "is bad" string for those romset which needs addition parts or device roms.

**Comment by Klezstyle** [comment]
To me that looks like to this mametesters bug:

"mame -verifyroms lists nonexistent roms / clones as bad"
https://mametesters.org/view.php?id=5556

**Comment by mackonsti** [comment]
I read all your comments but according to the official MAME FAQ there is no mention of these other romless machines or other ROMs that are shown on-screen when testing the items in "roms" folder, hence my original confusion. I agree with @Klezstyle for looking like the same issue. Thanks to both, hope a developer can reply.

**Comment by Robbbert** [comment]
MAME64.exe -verifyroms >> list.txt

should be

MAME64.exe -verifyroms > list.txt

**Comment by mackonsti** [comment]
Hi @Robbbert I agree, sorry it was a typo, been used from Linux :-)
Either way, I first run on-screen (CMD.exe) to see the results, without a file involved.
I get many ROM names that I have no idea where they come from, nor ever installed as boot-ROMs or other. Still referring to a clean MAME x64 installation... Thanks!

**Comment by cuavas** [comment]
It's behaving as expected.

**Comment by mackonsti** [comment]
Thanks @cuavas please kindly let me/us know, how to just validate the /roms/ folder instead?
I mean, how do we not include the other mentions as they appear currently? Thanks!

**Comment by cuavas** [comment]
You'd probably be better off with an external tool.  MAME is not a comprehensive ROM set management tool.  Have you looked at ROM Center, ClrMAMEPro, or the ROM management features of qmc2?

**Comment by mackonsti** [comment]
Yes, I have experimented with ClrMAMEPro but the zips re-created (merged etc.) don't validate them properly, especially with MAME v2.0.x or later a lot of (newly required) files are missing from packaged ROMs (bin, key etc.) that don't get indicated otherwise; only MAME mentions them as now required. Anyway, validating with **-verifyroms** even in this way, is still helpful.
Thanks again for your replies.
