### ISSUE TITLE
Document how to build individual tools

### ISSUE THREAD

**Issue by hadess** [mamedev/mame#5476]
While trying to make some modifications to imgtool, I ran into the problem that I could not find how to compile just this tool. The default build takes more than 30 minutes on my laptop where I made the imgtool modifications, and it would have been beneficial if I knew how to build just the tool I needed.

I tried reading the README as well as one of the more format documentations, and could not find the information.

If somebody tells me how to do this (or how to find the different targets), I'd be happy to modify the README or the documentation in a PR.

**Comment by Tafoid** [comment]
It is only built as a part of the TOOLS=1 make flag along with the dozen or so other tools part of the sourcetree.  It should go quickly if you already have a compiled binary's object files.  If not, it will compile only what is needed to make the all the tools.
.
https://docs.mamedev.org/initialsetup/compilingmame.html?highlight=tools

**Comment by hadess** [comment]
>  It should go quickly if you already have a compiled binary's object files. If not, it will compile only what is needed to make the all the tools.

I don't care for the rest of MAME though, I wanted to only compile the imgtool binary, nothing else. Or at least just the tools, and not the emulators.

**Comment by hadess** [comment]
I've used this, which speeds it up a bit, but I wish there was a way to compile just the tools. I don't understand the build system either...
```sh
$ make SUBTARGET=tiny TOOLS=1
```

**Comment by Tafoid** [comment]
That would be the best way short of making a SOURCES= build  - which will compile only the source files (separated by a comma) you signify as a SUBTARGET.  Most Developers when working on a particular driver find it much faster to compile only the source file(s) they are working on rather than wait for a long link time.

Documents include some info about it under compiling for Emscripten and other targets, but the commands works the same with mainline and normal OS'es
https://docs.mamedev.org/initialsetup/compilingmame.html?highlight=subtarget

Example:  SUBTARGET=commodore SOURCES=src/mame/drivers/c64.cpp

Hopefully this helps.  AFAIK, there is no way to NOT compile source in some way to get tools.  A good portion of the core is used in its production (unidasm for example).

**Comment by rb6502** [comment]
As Tafoid said, most of the tools rely on the MAME core and HAL layers so you have to build all of that first.  There is no way to build only tools.

**Comment by npwoods** [comment]
Shouldn't 'make TOOLS=1 imgtool[.exe]' work, and while the MAME core would be built, wouldn't that bypass 95+% of the code?

**Comment by rb6502** [comment]
Nope.  The build system is built to expedite working on drivers, not the tools.

**Comment by rb6502** [comment]
(Meant to click Comment, not Close...)

**Comment by cuavas** [comment]
It's possible to build individual tools if you set the right environment variables and then run make from the right subdirectory inside the build directory.  It isn't straightforward though.  It's the kind of thing where if you really want to do it, you can work out how, but if you can't work out how on your own you'll probably have trouble doing it anyway.  Yeah, the "make driving GENie driving make" build setup is a pain.

**Comment by hadess** [comment]
>  It isn't straightforward though. It's the kind of thing where if you really want to do it, you can work out how, but if you can't work out how on your own you'll probably have trouble doing it anyway.

If working out how is longer than building the thing once, then it's probably not very interesting. I've created a script to run `make SUBTARGET=tiny TOOLS=1` for me to test my imgtool changes. Thank you all for the discussion nonetheless :)
