### ISSUE TITLE
USB input device settings stripped out when MAME is launched without device

### ISSUE THREAD

**Issue by rain-1** [mamedev/mame#5531]
If you set custom keys for a USB input device like an arcade stick it saves those settings.

If you launch mame without that input device plugged in your settings are stripped out and you need to redefine them all next time you plug in the input device.

It would be better if the settings stayed and were not stripped out.

**Comment by rb6502** [comment]
MAME used to work the way you want.  Result?  People complained that they were unable to control MAME because it was looking for controllers they didn't have plugged in.

You may either set your .cfg file to read-only after configuring the device or read up on our "Stable Controller IDs" feature: https://docs.mamedev.org/advanced/devicemap.html

There are some good tutorials on YouTube on how to use the Stable Controller IDs feature as well.  Good luck!
