### ISSUE TITLE
Improve offscreen reload for Wiimotes.

### ISSUE THREAD

**Issue by elsonrodriguez** [mamedev/mame#559]
When using offscreen reload with a [Wiimote](http://blog.novaslp.net/post/97113634233/wiimotes-as-lightguns-in-mame-on-linux), one has to aim at the edge of the screen in order to trigger a reload. This is problematic given that the edge of the screen is also the edge of wiimote's usability.

Something useful does happen you aim offscreen with a wiimote though: the cursor doesn't move at all.

Would it be possible to make it so that whenever the cursor hasn't moved at all for a few (configurable) milliseconds, that this sets the lightgun to "offscreen"?

**Comment by rb6502** [comment]
I think this would greatly violate the principle of least surprise in a fairly major way.  There's no precedent in the Wii's software library for a still Wiimote to randomly warp offscreen, and in some of the slower-paced MAME lightgun games if you wanted to line up a shot and keep it there, having the pointer suddenly warp offscreen would be quite upsetting.

And of course since we don't know the difference between Wiimotes and arcade light guns, *those* users would really find this weird.

**Comment by h0tw1r3** [comment]
A hack like this would ideally be a lua plugin. Would just need to extend lua with crosshair_position on the ioport:field table.
