### ISSUE TITLE
Unable to build shaders with latest BGFX

### ISSUE THREAD

**Issue by MooglyGuy** [mamedev/mame#5738]
```[MINGW64] C:\mingw\mame>make shaders CHAIN=misc
GCC 7.2.0 detected
"==== Building bx (release64) ===="
Archiving bx
"==== Building fcpp (release64) ===="
"==== Building glslang (release64) ===="
"==== Building glsl-optimizer (release64) ===="
"==== Building spirv-opt (release64) ===="
"==== Building spirv-cross (release64) ===="
"==== Building shaderc (release64) ===="
Cleaning...
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

[MINGW64] C:\mingw\mame\src\osd\modules\render\bgfx\shaders>```

**Comment by belegdol** [comment]
can you try editing 3rdparty/bgfx/scripts/tools.mk and removing one of the two slashes in the cmd //c call?

**Comment by MooglyGuy** [comment]
That seems to have fixed it. Thanks!

**Comment by belegdol** [comment]
Were you running make shaders from within MSYS2 shell? We need a better fix here because on my Win10 install one shader leads to issue described here:
https://superuser.com/questions/526736/how-to-run-internal-cmd-command-from-the-msys-shell
So unless I am doing something odd, we might need some more logic added to the makefile.

**Comment by MooglyGuy** [comment]
I was running it from the shell which is entered via "win32env.bat" in the msys64 subdirectory.

**Comment by belegdol** [comment]
Now I know what happened. I missed the fact that the official supported way of building mame is to use the cmd shell, not bash. In bash you need double slashes, in cmd - single.
I am going to submit a PR fixing this mess.

**Comment by LuismaSP89** [comment]
@MooglyGuy Sorry for the offtopic, but this PR is supposed to be the previous job to make 6xbrz shaders working again in MAME? 

Thanks a lot.

**Comment by MooglyGuy** [comment]
If they still don't, please file a separate bug. Thanks!

**Comment by LuismaSP89** [comment]
@MooglyGuy The xbrz filters need to be created again since the 0.193 changes in the BGFX backend. There are currently 6xbrz shaders for Opengl, but they're not so smooth as the 6xbrz filters for BGFX. And the BGFX backend is the more reliable and accurate backend for MAME.

I post a bug a year ago, I don't know if you remember this:

https://github.com/mamedev/mame/issues/3920

PS: Thanks a lot for your quick reply ; )
