### ISSUE TITLE
Glitches in King of Fighters 2000 and 2002

### ISSUE THREAD

**Issue by jstolarek** [mamedev/mame#5981]
I am experiencing graphical glitches in King of Fighters 2000 and 2002:

![kof2000-191128-113251](https://user-images.githubusercontent.com/1597921/69817720-242ee680-11f3-11ea-81db-467955d40b44.jpg)
![kof2000-191128-113256](https://user-images.githubusercontent.com/1597921/69817721-24c77d00-11f3-11ea-8123-d4b4a6030889.jpg)
![kof2002-191128-115059](https://user-images.githubusercontent.com/1597921/69817723-24c77d00-11f3-11ea-9ef6-efcaa98deb4a.jpg)

In KOF 2000 these always (100% reproducibility) happen at the beginning of a fight, at the end of a fight and on various screens in between the fights (so basically everywhere except for the fights themselves). I haven't tested KOF2002 that heavily but the glitches definitely happen at the beginning of a fight as well. KOF 98 and Last Blade 2 seem to play fine though. Each of the glitches is a single frame (though sometimes there are two different glitches one after another). Notice how the glitches extend beyond the normal screen area. This happens with MAME 0.216 (though screens themselves were taken with RetroArch MAME core).

**Comment by jstolarek** [comment]
Also, screenshots were made with an upscalling filter enabled but it's the same without any filters.

**Comment by happppp** [comment]
There's a view option in video option to hide the edges. Should we hide neogeo.lay screen edges by default? (if yes, crop or stretch?)

**Comment by MooglyGuy** [comment]
Neo-Geo games did not always make full use of the entire area to which the video chip could render. This is an artifact of these games being displayed on what amounted to an analog display device - a cathode-ray tube (CRT) - which could and did have its scanned, displayable area adjusted on a per-game basis.

I would suggest you familiarize yourself with how these vintage systems worked, by way of such analogous explanations as this: https://www.youtube.com/watch?v=wfrNnwJrujw

By default, MAME displays the entire renderable area of the Neo-Geo's video chip, as there were a few games which drew meaningful graphics out to the entire limits of the screen. King of Fighters 2000 and 2002 is obviously not one of these titles.

In any event, this is not a MAME bug, and this issue is closed.

**Comment by cuavas** [comment]
> Should we hide neogeo.lay screen edges by default?

It shouldn't.  Games developed with SNK's tools use 304 horizontal pixels, but some third-party titles (e.g. Puzzle Bobble) use the entire 320 horizontal pixels.

**Comment by jstolarek** [comment]
> Games developed with SNK's tools use 304 horizontal pixels, but some third-party titles (e.g. Puzzle Bobble) use the entire 320 horizontal pixels.

Ah, now I get it. I tried putting the cropping setting:

```
<video>
    <target index="0" view="Screen 0 Cropped (304x224)" />
</video>
```
into a master NeoGeo config file, so that I don't have to set it individually for each game. But that setting got ignored and now I understand why. That being said, is there any documentation that would allow me to discover which settings can be applied on a system-wide basis and which are game-specific? Pointer to a source location is also fine.

**Comment by cuavas** [comment]
You need to use an INI file, not a CFG file (see [here](https://docs.mamedev.org/advanced/multiconfig.html) for some information on how INI files are loaded).  You probably want to create `source/neogeo.ini` and put this line in it:
```
view0 Screen 0 Cropped (304x224)
```

**Comment by jstolarek** [comment]
Thanks. Again, any way for me to discover what setting can be put in a file? I would not have figured out the `view0 Screen 0 Cropped (304x224)` line by myself.

**Comment by cuavas** [comment]
All the things listed by `mame -showusage` can be configured in an INI file.
