### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [mamedev/mame#6102]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [avivideo_image_device::call_unload](https://github.com/mamedev/mame/blob/1a5bf558cc9889c2f45a6c0eea68a00615ac5e1e/src/devices/imagedev/avivideo.cpp#L106 "avivideo_image_device::call_unload function")
- [picture_image_device](https://github.com/mamedev/mame/blob/909bfe98904ffb47c020d054faf9cfcaf9ad57b5/src/devices/imagedev/picture.cpp#L37 "Destructor for picture_image_device")
- [text_buffer](https://github.com/mamedev/mame/blob/e64edf6c7127fb8291a157026f3ac72e38c78d80/src/emu/debug/textbuf.cpp#L38 "Destructor for text_buffer")

**Comment by cuavas** [comment]
You can also argue that it's pointless assigning `nullptr` to pointer members after deleting in the destructor because nothing will use it after that.  In the scale of things, it's so minor that it’s not worth opening an issue about.  If someone wants to get rid of the checks they can, but it’s not on the hot path and won’t be causing any issues.

**Comment by elfring** [comment]
How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?
