### ISSUE TITLE
confirm_quit option missing?

### ISSUE THREAD

**Issue by motoschifo** [mamedev/mame#617]
I have downloaded and compiled the latest version of Mame and the option -[no]confirm_quit was missing.
With -showusage option specified there is no text about this behaviour.

This is the result of command:
```
./mame64 -confirm_quit mslug
Error: unknown option: -confirm_quit
```

Is this an error?

**Comment by rb6502** [comment]
If it's the 0.170 release, end-user and emulation bugs should be reported at mametesters.org.  We try to keep this "Issues" section for technical things such as the recent 68020 instruction screwups.

If it's a random GIT pull, those aren't supported; the integration of MEWUI is still very much a work in progress and we aren't accepting bugs on that prior to 0.171.

**Comment by stilett0** [comment]
Coincidentally I've been investigating the history of this very option.

It appears that the development of the option was developed by MAMEPlus team in some of the following commits to their code, then submitted and added to MAME itself.
http://mameplus.svn.sourceforge.net/viewvc/mameplus?view=revision&revision=264
http://mameplus.svn.sourceforge.net/viewvc/mameplus?view=revision&revision=271
http://mameplus.svn.sourceforge.net/viewvc/mameplus?view=revision&revision=272
http://mameplus.svn.sourceforge.net/viewvc/mameplus?view=revision&revision=950

... eventually crediting "MAMEPlus Team" (as well as MameSick of MAMEUIFX) in our changelog. Since that's a bit generic, (in our zeal for finding all major and minor contributors ever) I wanted to see who _actually_ was responsible. I can't find the history of the option prior to MAMEPlus rev. 264, but it looks like I have some candidates for developers within their team

Anyhow, that's all sidebar: if the feature has been removed, it's news to me. Possibly a casualty of the MEWUI merge, which as Arbee said is very WIP so we aren't accepting bugs on that yet.

**Comment by etabeta78** [comment]
I was the author of our implementation, inspired by MAMEPlus and UIFX code.
No "direct code" was used from their source, even if similarities are
unavoidable being a very simple option check at ESC pressure ;)

    f.

**Comment by stilett0** [comment]
Okay thanks eta. ;)

**Comment by mmicko** [comment]
Since this is UI related I have moved it to ui_options and those are not exposed as command line params, but can be changed using UI itself or by editing ui.ini
