### ISSUE TITLE
Recommended Linux distribution for compilation

### ISSUE THREAD

**Issue by jotego** [mamedev/mame#6901]
I'm increasingly running desperate as I still have not had success in compiling MAME after 5 days. Would it be possible to specify in the [documentation](https://docs.mamedev.org/initialsetup/index.html) an exact linux distribution, along with its version, where compilation works out of the box?

Something like:
```
Use Ubuntu 16.04
Add these packages: sudo apt install foo foo
Run: make
```
Because the current recommendations for Ubuntu just don't work. I don't mind installing a different linux flavour as long as I can make it work.

**Comment by Osso13** [comment]
It worked out of the box for me on more recent Ubuntu versions. I just need to add -U_FORTIFY_SOURCE as a compile option. (see https://github.com/mamedev/mame/issues/4191)

**Comment by jotego** [comment]
Thank you for that piece of advice. I have been able to make it work with:

```
make REGENIE=1 CFLAGS='-U_FORTIFY_SOURCE'
```
On Ubuntu 20.04.
I have added this to the documentation ([pull request](https://github.com/mamedev/mame/compare/master...jotego:patch-1)).

Thanks again. I'm really glad it works now!

**Comment by colinhowell** [comment]
This should not have been closed just yet. The documentation has an oversight that needs to be fixed, or else the submitter would have been forewarned of this problem and been able to solve it without help.

@cuavas closed #4191 with a comment about how certain Linux distros create this problem by patching GCC to define _FORTIFY_SOURCE as a macro, changing GCC's behavior for all compilations whether they need it or not. That note has already been added to the "Compiling MAME" page in MAME's documentation, but it's sitting near the bottom in its own subsection under "Known Issues". Most users compiling MAME are not going to read that far initially without prompting. Since this problem affects several versions of Ubuntu, one of the most popular of Linux distros, it should be mentioned in the "Debian and Ubuntu" subsection with a note saying something like:

> On Ubuntu versions [_versions affected_], compiling MAME with the distro's GCC requires overriding its redefinition of `_FORTIFY_SOURCE` by including `-U_FORTIFY_SOURCE` in the compiler flags for the make command line. [_Reword these directions as appropriate._] See **Known Issues: GNU C Library fortify source feature** [_link to the full note_] for more details.

I haven't fleshed this out fully because I haven't checked all the specifics. The point is that the user compiling on Ubuntu is likely going to read the Ubuntu subsection first and, seeing no obvious warnings, will just go ahead. That section is your chance to warn him, "hey, you're probably gonna run into this wrinkle, so do _this_ to work around it; also, see _this note_ if you want to learn more."

**Comment by cglmrfreeman** [comment]
I've been compiling with OpenSUSE with no official documentation. Just requires a bit of legwork in finding which devel packages zypper needs. I don't see why a "recommended" distro is needed if many flavors of Linux have prebuilt packages from a variety of sources. Would a recommended distro be favored heavily by the development team? Would "Overhaul of various distro compilation instructions" be more what you're looking for?

**Comment by colinhowell** [comment]
At this point, the issue is really about fixing an oversight in the distro-related build instructions, not about recommending a distro. That was just the original poster's request, in order to find a solution to a problem that they had been unable to resolve.

**Comment by rb6502** [comment]
This shouldn't have been re-opened; just submit a PR that changes the documentation.
