### ISSUE TITLE
Simpsons.ccp, Potential Typo?

### ISSUE THREAD

**Issue by DemmyTree** [mamedev/mame#6913]
I've been looking at the simpsons ccp to see if there was any way to create an option for switching between two and four players when i came across what may be a typo however I am unsure

In the dialog under input options simpsons2p controls come under simpsn2p, I have tried to look through the repo to see if i could find this anywhere else,

in simpsons.c line 442 there is a mention of simpsn2p as well as line 180 for the input, would this impact on the test switch option for player selection. I wondered if this could be a case where because the file name does not match the rom upon reset from testswitch config the ram should then load the 2p version of the game

If not out of curiousity would an if statement work for gameload (If ControllerDetect=2 Load simpsons2p else if <3 load Simpsons

I have hardly any knowledge with coding but this caught my attention and thought it was best to share.

Enjoy Simpsons but wondered if this is the same for alternate games as well where there is no dipswitch tied to the board.

**Comment by happppp** [comment]
Hi,

I think you're viewing an older version of the source file, because the line numbers don't match. Here is the current version:
https://github.com/mamedev/mame/blob/master/src/mame/drivers/simpsons.cpp

No, the naming of the input ports won't have any effect. For example it could be named "bart" and it would still work the same. I see an outdated comment saying "simpsn2p" on line 572, source code comments don't have any effect on the MAME program.

No, auto-loading the 2 or 4 player romset depending on number of controllers detected with a single line statement won't work. Not trying to be funny here: it will work for humans. Detect how many controllers you have connected, and decide to load the romset. That's not much work at all.
