### ISSUE TITLE
Enabling automatically multithreading on suitable PC's

### ISSUE THREAD

**Issue by Sworddragon** [mamedev/mame#710]
From the manpage the option -[no]mt is disabled at default but maybe the default can be changed to automatically detect if multiple cores are available and enabling multithreading in that case.

**Comment by ppriest** [comment]
This option was experimental when it was added - there are several bugs solely as a result from it. I'd recommend that it be removed entirely. Just do a search for "-mt".

**Comment by Tafoid** [comment]
multithreading or -mt, in this case, is not directly linked to processor CPU cores, but allows them to be used for graphics processing.  The command causes the window and all Direct3D code to execute on a second thread, which can improve performance on hyperthreaded and multicore systems. The default is OFF because there are some machines which do not function properly with it and cause graphic emulation problems where they didn't exist before.  It is strictly use as your own peril at this moment and as ppriest mentioned - it will likely be removed entirely.
