### ISSUE TITLE
CDI driver: recent commit breaks previously working game (The Apprentice)

### ISSUE THREAD

**Issue by WeedyWeedSmoker** [mamedev/mame#7183]
Hi!

This commit https://github.com/mamedev/mame/commit/4be9b4b298e488560a34bf5a6914d7e060990500 breaks The Apprentice (tested `apprentc/the apprentice (cdi-ready).chd` with `cdimono1.zip`)…

Works fine when reverting this specific commit _(as well as https://github.com/mamedev/mame/commit/1496a22bc04d3754db50e16c8f43f31877c247da because there's a conflict with `/src/mame/machine/cdicdic.cpp` when reverting only https://github.com/mamedev/mame/commit/4be9b4b298e488560a34bf5a6914d7e060990500 )_…

Thanks!

**Comment by DavidHaywood** [comment]
The Apprentice CD image should be considered a bad dump because the cue/bin format the CHD was made from can't properly represent data in what the CD-i Ready format, which is data in what is considered the pregap of an the first track, which is specified on disc as an audio track rather than data.  (some music CDs use the same trick to hide audio before 0 on the CD as a secret music track, CD-i ready uses it to hide data so that most CD players skip it)

**Comment by WeedyWeedSmoker** [comment]
@DavidHaywood That makes sense… I understand better what is the CD-i ready format thanks to your explanation!

If I understand correctly, only a handful of discs used this format? Would we need an update to the CHD format to be able to store such an obscure (and not very popular) format?

From the cdi.xml hash file:
> Trying to convert this in CHDMAN from the cuesheet results in a mangled CHD, with incorrect offsets when trying to output it again.
> 
> Manually adding a pregap area to the cuesheet encodes it without mangling the offsets, but still doesn't result in anything that boots.

Does that mean it would boot with just a change to the cuesheet and advancements in MAME's cdi driver or should we try to find a way to dump the CD properly?

Thanks again for your perfectly clear explanation of the situation!

**Comment by DavidHaywood** [comment]
I suspect it will need converting from a source format that can natively handle it (ie one not based on the concept of cuesheets at all, but using the raw data on the disc stored in the area that the drives use to determine that)    both CHDMAN and the driver will need updating to support that.

I'm not an expert in this field, but I'm just giving you a likely reason why improvements could have broken the game for now, as I have doubts it would work 'as is' on a real system.

**Comment by MooglyGuy** [comment]
cdimono1 is marked as MACHINE_NOT_WORKING in order to avoid exactly these sorts of issues.

**Comment by smf-** [comment]
IMO we should just change chdman into a streaming archiver that stores
the cue/bin and parse them at run time. We can use information from the
cue to try to improve the compression, but it should be lossless.

At least then every time we realise we've been doing it wrong, we don't
have to dump all the games again and again and again.

**Comment by WeedyWeedSmoker** [comment]
@MooglyGuy Of course… I thought of a regression in the driver but it's more of an advancement if the bad dumps start to require a more proper one…

This is encouraging anyway!

**Comment by rb6502** [comment]
No, the driver actually is broken.  This disc format stuff is a separate issue, it's not why the game stopped running.

**Comment by Darknior** [comment]
Hi, we are near in 2022... and this game is always broken :(
Impossible to launch it with actual MAME engine.
And from this commit : https://github.com/mamedev/mame/commit/4be9b4b298e488560a34bf5a6914d7e060990500
The two Zelda are break too.
3 great games of CDi are down from a long time ... and i have must to search a lot to understand i will must use an old mame 221 :(
Do you think CDi will be fixed soon ?

**Comment by MooglyGuy** [comment]
Not very soon, no.

There are games that the commit is documented as helping, and games that the commit is documented as harming. Which is the correct call - break one set of games, or break another set of games? Regardless of which choice I make, people will complain.

Perhaps I should just remove the driver entirely, then everyone can be equally unhappy.

**Comment by Darknior** [comment]
@MooglyGuy  for sure i understand fine, it is complicated.
But is there a way to have a choice, an option in MAME menu to switch from the two systems ? Like the problem that make the two Zelda very slow ... 
Now i know the problem i will compile an old 221 build, but it has been not easy to understand why some by the past play these games and now it is impossible.

**Comment by rb6502** [comment]
This isn't like that. From what MG has learned, the behavior of the emulation now is more correct than it was.  It's not uncommon for correcting some errors to expose others that were previously being hidden and cause software to stop working.  Just keep a binary of 0.221 around if you want to play whatever's broken now, unless you're secretly Jeff Bezos and would like to send Moogly a lot of money to dedicate his time to CDi.

**Comment by MooglyGuy** [comment]
Such an option will not be added. That sort of thing has been done in the past, and it's always worked out poorly: It increases the burden of code maintenance, it makes the codebase less clear for developers, and inevitably MAME ends up saddled with two implementations in perpetuity.

If you really want to emulate the CD-i, you should go with CD-i Emu for now, rather than bothering with an older version of MAME. MAME's emulation of various CD-i games has never been particularly good, which is why when you start the driver, you encounter a big red box that has all-capital text specifically saying that the driver does not work, as shown below.

![cdimono1](https://user-images.githubusercontent.com/1891617/143795194-5e5ec8cd-152b-4611-a58b-8190d6ac2145.png)

**Comment by Darknior** [comment]
I understand, but a red box is not fixing problems :)
It only warn the user, ok, and you write the CDi is not fine emulated on MESS, for sure all the games i have tested are working really fine, with no bug, MAME emulate fine CDi but some games have little bugs and it is harm to let it broken.
For sure i can use an old version, an other emulator, but for my part i want to use MAME because on our project we use it for many other machine, and it works fine.
If you want an other game with a bug, Alice has one, the game launch fine, works fine, you can move etc, but you cant use buttons 1 2 or 3 ... they are not working, and you can't do anything. I will try it in 221 to see if it's same or not.
But CDi is a good console, so bad so many people are working on it, some many guys hate CDi, it is a part of the video game story, i wish one day it will be possible to use MAME to work it easily :)

**Comment by MooglyGuy** [comment]
The literal point of that warning screen is so that users don't report bugs, so personally, I actually don't want another game with a bug, thanks.

**Comment by WeedyWeedSmoker** [comment]
@Darknior It's a good thing people from the MAME team work on CD-i emulation, as they are the best at recreating the whole thing as accurately as possible…

There are some other solutions out there, and they will certainly benefit from MAME's team work!

For The Apprentice, I found this Windows port (which works great under Wine) : https://www.shikotei.com/?p=TheApprenticeProject, and if I want the old broken MAME implementation, I just revert the commit…

**Comment by angelosa** [comment]
I am missing something there other than The  Apprendice is marked with `supported=no` and `status=baddump` -> needs a redump that includes CDi Ready data?

**Comment by rb6502** [comment]
Kale: it doesn't need a redump in order to run.  CDi Ready is purely a stick up Haze's butt that doesn't actually impact emulation quality.  Yes, we'll want to address it in the future, but I can wait for LibAARU to be ready before I do anything major to how CDs are represented.

**Comment by DavidHaywood** [comment]
CHD can't support CDi-Ready (all game data is in the first audio track pregap, with the first audio track being an actual audio track the game uses) so the track numbers are off with the current image, which I hacked to use regular audio tracks.

Windows etc. sees the CD as all audio tracks usually, if you 'rewind' on a CD player you get the garbage noise of the data.  The image in the softlist instead has track 1 as data.

But that's probably not why it's broken, it is however why the dump is marked as bad.

**Comment by Darknior** [comment]
> @Darknior It's a good thing people from the MAME team work on CD-i emulation, as they are the best at recreating the whole thing as accurately as possible…
> 
> There are some other solutions out there, and they will certainly benefit from MAME's team work!
> 
> For The Apprentice, I found this Windows port (which works great under Wine) : https://www.shikotei.com/?p=TheApprenticeProject, and if I want the old broken MAME implementation, I just revert the commit…

Thanks a lot, yes i know it, like there are also two remake of Zelda and Link now with  a better gameplay.
But i'm on a linux system, for sure we have try and they works fine with Wine lol
But i really prefer playing the real game on MAME :) stock with other CD-i games. 
I will try the v221 because some other games are also in CDi-Ready and not start with the last version.

**Comment by rb6502** [comment]
Again, CDi Ready is not why the games don't work.

**Comment by DavidHaywood** [comment]
well it could be if the CD code attempts to play track 1 as audio, when track 1 is data in the hacked image, and now fails in such a case, as I don't think anybody ever verified that the hacked image boots on hardware, but it is unlikely to be the issue.

**Comment by WeedyWeedSmoker** [comment]
The french site GameTronik managed to rip The Apprentice correctly only in the CloneCD .img/.sub/.ccd format…

It's the only place I found a proper console tested rip

```
Track (01)	audio	15:24:00	LBA=069150
Track (02)	audio	19:46:00	LBA=088800
Track (03)	audio	23:57:00	LBA=107625
Track (04)	audio	24:58:00	LBA=112200
Track (05)	audio	29:44:00	LBA=133650
Track (06)	audio	30:45:00	LBA=138225
Track (07)	audio	35:33:00	LBA=159825
Track (08)	audio	36:39:00	LBA=164775
Track (09)	audio	41:14:00	LBA=185400
Track (10)	audio	42:17:00	LBA=190125
Track (11)	audio	46:27:00	LBA=208875
Track (12)	audio	47:22:00	LBA=213000
Track (13)	audio	51:38:00	LBA=232200
Track (14)	audio	52:38:00	LBA=236700
Track (15)	audio	53:47:00	LBA=241875
Track (16)	audio	56:57:00	LBA=256125
Track (17)	audio	57:07:00	LBA=256875
Track (18)	audio	59:04:00	LBA=265650
Track (19)	audio	59:27:00	LBA=267375
Track (20)	audio	60:02:00	LBA=270000
Track (21)	audio	60:24:00	LBA=271650
Track (22)	audio	60:59:00	LBA=274275
Leadout: 62:06:00	LBA 279300
```

**Comment by Darknior** [comment]
@WeedyWeedSmoker i've already do it and it works fine if the Rip is good. Convert it with IsoBuster to ISO+CUE and after you will can convert it in CHD and it will works fine. It IsoBuster make some errors it will not works fine...
I already have this image, i must try it on 221 to confirm or not if the game working fine?

**Comment by cuavas** [comment]
This has gone way off-track.  Take it to a forum or discord or something.  The system is marked not working, the commit in question reflects a better understanding of the hardware.  You can always by CD-i Emu if you really need a working CD-i emulator.

**Comment by angelosa** [comment]
https://github.com/mamedev/mame/commit/022361c6830f6b60c050f019f8e660da9f8ce3d9#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26 fixes what has been reported in this issue anyway.
