### ISSUE TITLE
can't defeat a boss in Silk Worm

### ISSUE THREAD

**Issue by 280696516** [mamedev/mame#7286]
in game Silk Worm (World), Wave-10, I take a long time to attack the boss,but I can't destory it. If I cheat,turn on "P1 Invincibility",the boss can be destoryed.
![0000](https://user-images.githubusercontent.com/54297406/94192357-6d1dfd00-fee1-11ea-85cd-179b328b822f.png)
Is it a mame bug?

**Comment by angelosa** [comment]
1. testing off games with cheating on only is bad practice and known to give unexpected side effects in the normal execution of the game flow. 
2. In this specific case: if you wait too long with invincibility cheat on (and crash into it?) then any boss becomes impossible to kill, presumably due of how the rank system works out here (reported in area 2);
3. gameplay intensive bug reports really belongs to [MAMEtesters](https://mametesters.org/)
4. BBH did a [1cc/wave 12 clear](https://www.youtube.com/watch?v=BF8ZyvhXV78) just 2 weeks ago. The only caveat is that he used the jeep instead of the heli, and I do recall that heli was reportedly buggy even on real HW, I'll ask for confirmation because I don't remember the full story atm.

**Comment by angelosa** [comment]
![0000](https://user-images.githubusercontent.com/9251271/106948480-0c72bc80-672c-11eb-92c7-74b74cc5a33a.png)

Boss 10 is nasty but doable (and really the first thing that triggered the time out rank in my test run), also you're supposed to reach there by not continuing from area 7.
Nothing to fix here, and prolly not even worth to post to [MT](https://mametesters.org/)
