### ISSUE TITLE
Error: unknown option: -midiout

### ISSUE THREAD

**Issue by GuckTubeYT** [mamedev/mame#7347]
when i do mame64 -listmidi
its shows this
MIDI input ports:

MIDI output ports:
Microsoft MIDI Mapper (default)
Microsoft GS Wavetable Synth
MT-32 Synth Emulator
BASSMIDI Driver (port A)
BASSMIDI Driver (port B)

but, when i type this mame64 -midiout "MT-32 Synth Emulator"
i got an error = Error: unknown option: -midiout

**Comment by GuckTubeYT** [comment]
i do --midiout "MT-32 Synth Emulator" too
still same

**Comment by MooglyGuy** [comment]
I believe you must first be running a system that supports MIDI input or output before those options will be available.

**Comment by GuckTubeYT** [comment]
> I believe you must first be running a system that supports MIDI input or output before those options will be available.

when i do -listmidi = its detected
but, when i do -midiout = doesnt work

**Comment by MooglyGuy** [comment]
That's not what I asked. Show the command line that you're using to start the specific system that you want to use with MIDI output.

**Comment by galibert** [comment]
-listmidi shows every midi interface of the host system mame can
potentially connect to.  It thus doesn't need an emulated system.

-midiout<n>, -midiin<n> actually connects a port of the emulated system to
the host.  So an emulated system is required.

That's why a pure "mame -listmidi" works and a "mame -midiout <x>" won't,
you need a system for the second, like "mame esq1 -midiout <x>"

  OG.

**Comment by GuckTubeYT** [comment]
when i look on another forum website = it use -midiout

**Comment by cuavas** [comment]
`-midiout` is a media option provided by systems/devices that have MIDI output ports.  It is not a global MAME configuration option.  You must supply a system name (and possibly slot configuration) that has a MIDI output port for this option to be available.
