### ISSUE TITLE
unidasm: add endianness swap option

### ISSUE THREAD

**Issue by caps0ff** [mamedev/mame#7394]
MAME internally swaps some ROM endianess (ie ROM_LOAD16_WORD) but unisasm isn't aware of this swap. For example, taking https://github.com/mamedev/mame/blob/master/src/devices/sound/bsmt2000.cpp and running unidasm on the raw binary:

```
$ unidasm -arch tms32010 bsmt2000.bin  |head
000: 00f9       dw   00F9h *(invalid op)
001: 0400       add  00h,4
002: 00f9       dw   00F9h *(invalid op)
003: 960d       mpyk 160Dh
004: 817f       mpyk 017Fh
005: 8a7f       mpyk 0A7Fh
006: 006e       add  6Eh,0
007: 8068       mpyk 0068h
008: 017e       add  7Eh,1
009: 6650       zals 50h
```

Gives invalid disassembly. But swapping on 16 bit words looks good:

```
$  unidasm -arch tms32010 bsmt2000_swap16.bin |head
000: f900 0004  b    0004h
002: f900 0d96  b    0D96h
004: 7f81       dint
005: 7f8a       rovm
006: 6e00       ldpk 0
007: 6880       larp 0
008: 7e01       lack 01h
009: 5066       sacl 66h
00a: 4064       in   64h,PA0
00b: 6664       zals 64h
```

So I have to do this swap manually and then feed it into unidasm. It would be nice if unidasm had a flag to do this swap to streamline disassembling.

**Comment by ajrhacker** [comment]
I added exactly such a flag to unidasm a while back: `-xchbytes`.

**Comment by caps0ff** [comment]
Thanks! I was under the impression that this hadn't been added and my version is very old. I'll try to update and follow up if this isn't what I'm looking for.

**Comment by ajrhacker** [comment]
The story of how the option came to exist is a bit odd. I implemented a version of it once, committed it locally to a feature branch, forgot about it and reimplemented it. I probably thought about submitting it in a pull request due to some trivial concerns, but ended up inadvertently pushing the second version after cherry-picking it for a pet project researching disk drive firmwares. I certainly don't regret having added it nowadays.
