### ISSUE TITLE
Apple II slot ROM mapping

### ISSUE THREAD

**Issue by gorlik** [mamedev/mame#7586]
mame git with rb6502 fixes #7566 and #7544. Thank you!
apple2gs with scsi card in slot 7, no devices attached.

Still one minor difference between MAME and real HW.
*cfff:0
*cc00.cc07
00/CC00:FF FF FF FF FF FF FF FF
*c700:0
*cc00.cc07
00/CC00:FF FF FF FF FF FF FF FF
on the real HW the above line returns the ROM data. On MAME a read from Cnxx is required.
*c700
*cc00.cc07
00/CC00:A2 20 A2 00 A2 03 A2 00

MAME requires a read in the Cnxx area to enable the ROM while in the real HW either a read or a write enables the ROM.
This is consistent with apple documentation (apple IIgs hardware reference second edition pg.186) that shows that just IOSEL# assertion enables the card ROM. 

Also, to be pedantic...
*cfff
00/CFFF:30
*cc00.cc07
00/CC00:FF FF FF FF FF FF FF FF
on the real HW reading from CFFF returns FF. Accessing CFFF immediately disables the ROM (same pg in the hardware reference manual)

BTW: @rb6502 Thank you for the fixes so far. In case I find additional issues, do you prefer I add comments to this issue or open a new one?

**Comment by rb6502** [comment]
Those were 1) a bug (it actually would've worked in slots 1 or 2 if set to Your Card) and 2) possibly different behavior from previous A2s (on the IIe and IIc, when the system ROM is mapped in at $C800, reading $CFFF must return the actual byte or Apple's diagnostics will fail.  The GS doesn't make much use of that area for system ROM that I've seen).

Fixed in https://github.com/mamedev/mame/commit/c0dee3c85674f12183d381d75b4174b0399dfbe5

Just go ahead and open new issues if you find anything else.  I feel like we're pretty close though.
