### ISSUE TITLE
No clear easy to compile a single emulated machine?

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [mamedev/mame#7614]
# Need

Run one emulated machine (Amstrad CPC).

# Action

Read the fine website!

https://www.mamedev.org/
https://wiki.mamedev.org/index.php/Main_Page
https://wiki.mamedev.org/index.php?title=How_MAME_Works
https://wiki.mamedev.org/index.php/System-Specific_Setup_and_Information
https://wiki.mamedev.org/index.php/Frequently_Asked_Questions
https://wiki.mamedev.org/index.php/Driver:Amstrad
https://github.com/mamedev/mame
and others

# Expected

Clear instructions about how to compile and work on a small subset (even one) of the possible emulated machines.

# Observed

* Found only one hint: `SUBTARGET=mess`. Compiling.
* Relatively fast machine (Intel 10th gen, SSD at 3GByte/s) compiles for eons (even with `make -j8`), stops with _error_ in a part that is totally unrelated to the machine I need (nubus, no such thing in a CPC). 
* Switching branches (from master to latest release branch then latest release tag) with git appears to cause compilation to _restart from the beginning_.
* Error still happens, no solution found on the net, reporting as #7612 
* I fix the code in nubus, conforming to https://wiki.mamedev.org/index.php/Submitting_Source_Code , taking as example how surrounding code was progressively fixed (small improvement, like the git history shows).
* I submit a PR. #7613
* PR rejected within 2 minutes with too short instruction to be useful.

# Result

* Not using MAME.
* Staying positive, opening this very issue so that things can be improved.

Thank you for your attention.

**Comment by Osso13** [comment]
Please read the docs at https://docs.mamedev.org/initialsetup/compilingmame.html

_You can do driver specific builds by using SOURCES=<driver> in your make statement. For instance, building Pac-Man by itself would be make SOURCES=src/mame/drivers/pacman.cpp REGENIE=1 including the necessary REGENIE for rebuilding the settings._

**Comment by cuavas** [comment]
> Clear instructions about how to compile and work on a small subset (even one) of the possible emulated machines.
> # Observed
> 
>     * Found only one hint: `SUBTARGET=mess`. Compiling.
> 
>     * Relatively fast machine (Intel 10th gen, SSD at 3GByte/s) compiles for eons (even with `make -j8`), stops with _error_ in a part that is totally unrelated to the machine I need (nubus, no such thing in a CPC).

You can use an arbitrary subtarget and `SOURCES=` to build a subset of drivers, e.g.
```
make SUBTARGET=amstrad SOURCES=src/mame/drivers/amstrad.cpp
```

Separate multiple source files with commas.  Most dependencies are resolved automatically when generating project files.  Admittedly this isn’t documented too well, but it’s pretty well-known.  Also, this is the kind of thing you should ask about on a help forum, IRC, etc. not open issues for.

>     * Switching branches (from master to latest release branch then latest release tag) with git appears to cause compilation to _restart from the beginning_.

Well yeah, core headers that everything depends on have changed on master since the release was frozen.  If a header that everything depends on changes, everything will need to be recompiled.

>     * Error still happens, no solution found on the net, reporting as #7612
> 
>     * I fix the code in nubus, conforming to https://wiki.mamedev.org/index.php/Submitting_Source_Code , taking as example how surrounding code was progressively fixed (small improvement, like the git history shows).
> 
>     * I submit a PR. #7613
> 
>     * PR rejected within 2 minutes with too short instruction to be useful.

It’s a known issue with a documented workaround.  There are multiple closed issues related to this which you failed to read.  Duplicate issues will be closed in short order.  Your “fix”, like others, didn’t consider potential interactions with the guest-side driver for the emulated device.

> # Result
> 
>     * Not using MAME.
> 
>     * Staying positive, opening this very issue so that things can be improved.
> 
> 
> Thank you for your attention.

You should take questions like this to a community forum.  This is not what the issue tracker is for.
