### ISSUE TITLE
BGFX docs?

### ISSUE THREAD

**Issue by the-namelessone** [mamedev/mame#7619]
where to find information for the mysterious BGFX?
Are we supposed to guess ALL mame.ini options like textures which need to be applied to WHAT screen chain etc etc
or where can we find docs for it?

This is all I find: https://docs.mamedev.org/advanced/bgfx.html

So you can expect questions like this if there are NO docs.
The different screen chains are not even explained there.

So as a result: we dont know what the screen chains do + we don't know what mame.ini settings each screen chain requires.

**Comment by the-namelessone** [comment]
So can a good docs page about BGFX be written or the current one be updated in order to make sure all my questions are not needed to be asked here?
I mean

- explanation what each screen chain is doing
-settings required for each screen chain, in case special cases like the lut texture

thank you

**Comment by MooglyGuy** [comment]
Your tone is needlessly hostile.

The most commonly-used chains are mentioned by name on the "bad" documentation to which you link, and are sufficient for the majority of use cases.

The number of people actively working on MAME's online documentation is unfortunately minimal, and due to reasons which I will not disclose out of respect for privacy, the person writing the majority of it is mostly unavailable.

Based on the fact that you went through every single screen chain simply to take note of the ones that you perceived as not working properly, it really comes off as though you went into this with a frame of offering destructive, rather than constructive, feedback.

Personally, I wrote the majority of the BGFX system in MAME, and I did not even know about the "bgfx_lut" option, because it was apparently added by another contributor and I was not informed about it. Had I known, it most likely would have been documented.

I'm unlikely to immediately get around to improving the BGFX documentation, due to the holidays, but I'll do my best to prioritize expanding it when I get back to MAME development.

**Comment by the-namelessone** [comment]
Hi

You totally understand it wrong!
I post all weird things I find here in order to find bugs. I have no knowledge of undocumented things, so they appear as bugs for me...

I have written a program that runs MAME with all possible command line options and ALL possible combinations of them.
It takes 3 screenshots of each game running automatically.
I examine them and weird looking images according to me, I report here.
So this is to find bugs easy in each MAME version (mostly concerning the -video options).
It can also detect non-working combinations of command line options or not the desired effect of them.

My apologies if you find my messages hostile, but they are really not.

**Comment by the-namelessone** [comment]
Thank you for writing BGFX, the crt-geom screen chain is INCREDIBLY close to a real arcade monitor!!!

**Comment by MooglyGuy** [comment]
Oh, I only wrote MAME's interface layer to the BGFX library. BGFX itself is the work of the ever-impressive Branimir Karadzic. Additionally, the crt-geom chain is simply a port of (I believe) cgwg's amazing shader into the more general-purpose syntax needed by BGFX in order to cross-compile for all shader types.

**Comment by the-namelessone** [comment]
Is there a website we can download compatible BGFX json files to run more screen chains in MAME?
