### ISSUE TITLE
0.227 -swpath not working

### ISSUE THREAD

**Issue by the-namelessone** [mamedev/mame#7622]
Hi

The -swpath command line option is not working at all in mame 0.227. I do NOT have a mame.ini file and want to use only -swpath from command line

1) If I run this command line:

**mame64 sms alexkidd -rompath 'F:\MAME\Roms' -swpath 'F:\MAME\Software'**

I get following output:

mpr-12808.ic2 NOT FOUND (tried in sms)
Fatal error: Required files are missing, the machine cannot be run.

The file "sms.zip" is in my Roms folder.
The subfolder "sms" is a subfolder of my "Software" folder
The "sms" subfolder contains "alexkidd.zip"

2) If I run following command line after copying the "sms" software list folder as a SUBFOLDER of my MAME roms folder, to get following folder configuration:

**mame64 sms alexkidd**

The file "sms.zip" is in my Roms folder.
The subfolder "sms" is a subfolder of my "Roms" folder
The "sms" folder contains "alexkidd.zip"

the game runs perfectly.

Is this a bug in -swpath? Why does it not use  'F:\MAME\Software' as I specified?

Thanks

**Comment by the-namelessone** [comment]
I think I didn't understand it correctly.
The arcade ROMs and Software List ROMs folder seem to be both specified in -rompath, separated by ";"
This works.

But what is the -swpath for? If it's not for the Software List ROMs, what software is this command line option for exactly?

thx

**Comment by Tafoid** [comment]
This is a misunderstanding of SWPATH command.
The SWPATH command is for denoting the default path for checking for images if you are using the File Manager,
The ROMPATH command handles location for machine roms as well as Software folder(s) - separated with ;

Your specific issue, at least in my testing, appears to be your ROMPATH (SWPATH) arguments are not being used because of the **'** symbol.  If they were **"**, you wouldn't have an issue.

Example:
**-rompath "d:\roms";"d:\software"** - this works
**-rompath "d:\roms;d:\software"** - this works
**-rompath 'd:\roms';'d:\software'** - will not work

To find out any command and it's usage, use the **-showusage** command which gives a brief description.

**Comment by Tafoid** [comment]
I'd also suggest not using this project's ISSUES system to ask what are essentially help questions and not legitimate bugs.   There are plenty of forums and other places that could help you on a more personal level.
