### ISSUE TITLE
0.227 hash hsi files

### ISSUE THREAD

**Issue by the-namelessone** [mamedev/mame#7631]
Hi

Since no forum, docs or anything can give an answer to this, I'm forced to ask here while it's not a mame issue.
But since there is no docs about this, it's indirectly a mame issue too...
Undocumented things are issues.

Why are there 5 hsi files in mame hash folder and what are they used for?
The files are a5200.hsi, intv.hsi, msx.hsi, msx2.hsi and nes.hsi

best regards

**Comment by the-namelessone** [comment]
-listsoftware command option does not seem to use them. It only uses the .xml files.
I can't find any other option, command or UI, in mame that can use those files.

Somebody can solve this mystery for me?

**Comment by happppp** [comment]
No you are not forced to ask here, exactly because it is not a MAME issue. Github issues is not for user support.
I will not spoil you with help any further. Please try on a forum.

While not an official MAME forum, the most-visited one I believe is https://www.mameworld.info/ubbthreads/ubbthreads.php?Cat=
reddit is also popular nowadays: https://www.reddit.com/r/MAME/
