### ISSUE TITLE
CPS 1 : Black pixels on Stirder and Knights of the Rounds

### ISSUE THREAD

**Issue by wwark** [mamedev/mame#7678]
Some black pixel are presents for Strider and Knights of the Rounds.
Is it link to the ROM proposed in Mame or something not well implemented ?

Knights of the Round (at the beginning of the second stage) - Visible on Mame v0.226 but not on the real arcade (More details on the github below):
https://github.com/jotego/jtbin/issues/170

Strider (during the first stage) - visible on Mame v0.226 and not seem visible on this video YT https://youtu.be/ccZLtMPDU_o?t=29 (More details on the github below):
https://github.com/jotego/jtcps1/issues/72

Thanks,

**Comment by happppp** [comment]
Hello,

Neither of these are ROM dump errors, they are errors by Capcom.

old bug report for Strider here, PCB owner confirmed that bug is normal behaviour: https://mametesters.org/view.php?id=1682
high quality video for knights of the round, the black pixel you saw on stage 2 is visible: https://mametesters.org/view.php?id=4016

**Comment by wwark** [comment]
thanks for your quick response and pointing those previous bug !
