### ISSUE TITLE
Leapster emulation instantly crashes on every firmware

### ISSUE THREAD

**Issue by zulc22** [mamedev/mame#7681]
```
PS E:\Games\MAME> .\mame64.exe -version
0.227 (mame0227)
```
Crash logs below for each ROM.

Universal
```
leapster_aux004b_w 0001
Fatal error: unimplemented FLAG 20290040 (04 type helper)
```

UK 2.1
```
leapster_aux004b_w 0001
leapster_aux004b_w 0001
leapster_aux004b_w 0001
Fatal error: unimplemented FLAG 20290040 (04 type helper)
```

German 2.1
```
leapster_aux004b_w 0001
leapster_aux004b_w 0001
Fatal error: op a,b,c (07 User ext) (38381436)
```

Spanish 1.0
```
leapster_aux004b_w 0001
leapster_aux004b_w 0001
leapster_aux004b_w 0001
Fatal error: unimplemented FLAG 20290040 (04 type helper)
```

**Comment by zulc22** [comment]
`leapstertv` also fails, but I'm unsure if the message would change with different firmwares; I can only start `leapstertv` from the console, because it doesn't show up in the GUI. When I launch the Leapster machines from the console, I don't get the option to select a firmware.
```
PS E:\Games\MAME> .\mame64.exe leapstertv
Fatal error: unimplemented LDB_S 6268 (0x0c group)
```

**Comment by zulc22** [comment]
The above errors also happen when cartridges are loaded, which shouldn't change anything because the Leapster doesn't crash without a cartridge, but still could be useful information.

**Comment by Tafoid** [comment]
The machines do not work.  This is already known.

They are clearly flagged as NOT WORKING, noted both when you select them in the UI and when you launch them, you'll see a RED warning screen telling you this fact that "**There is nothing you can do to fix this problem except wait for the developers to improve the emulation**."   Largely, all that is done at this point is basic documentation, machines can be launched and even have known dumped cartridges documented for future use - but nothing will work largely due to unimplemented opcodes/incomplete CPU core(s) as well as knowledge of how the machines work is not fully understood.

Closing.
