### ISSUE TITLE
[CVK1] Ibara (2005/03/22 MASTER VER..) - Coin Error

### ISSUE THREAD

**Issue by wwark** [mamedev/mame#7720]
This game show a blue screen with a text Coin Error when you try to add a coin.

Thanks,

**Comment by angelosa** [comment]
Coin chutes in CVK1 based HW are a bit fuzzy but definitely working with bleeding edge.
For the user: you need to hit '5' in a short interval otherwise you get a coin jam, which was a very normal "anti freeplay" mechanism for a 00s cabinet arcade user if he tried to lockpick instead of just inserting a coin. 

Closing, it's not a secret that [PORT_IMPULSE](https://github.com/mamedev/mame/issues/5802) is inherently [design](https://mametesters.org/view.php?id=1020) flawed.

**Comment by wwark** [comment]
Thanks for this information i will try it.

**Comment by Tafoid** [comment]
It will for certainly fail is you are holding fast forward or unthrottling your emulation..  I have recorded other machines do this and it is expected IMHO.  Before you attempt a credit, make sure you are running 100% and not unthrottled and make sure you are not still holding down the fast forward (Insert) to 'skip' the bootup sequences quicker.

**Comment by Tafoid** [comment]
Also
https://mametesters.org/view.php?id=6220

**Comment by wwark** [comment]
with @angelosa tips, i managed to add coin without problem.
Thanks !
