### ISSUE TITLE
PDP1 softwarelist XML

### ISSUE THREAD

**Issue by Duimon** [mamedev/mame#8084]
is there a way to create a pdp1.xml for the hash folder so I can load Spacewar! in the traditional manner?

I have tried unsuccessfully to create my own.

**Comment by ajrhacker** [comment]
A software list is not strictly necessary to load Spacewar, but it's still a good thing to have for this or any other computer driver in MAME. If you're interested in compiling the extant software images into a XML list, I recommend trying and submitting one as a pull request.

The main obstacle to adding a brand-new software list is that it also needs to be hooked up in the driver; fortunately, this step is normally quite simple. Since the paper tape image device is unique to this driver, it may itself need to be updated to properly support the `interface` attribute for the XML `<part>` tag, but that shouldn't be too tricky either.

**Comment by Duimon** [comment]
Unfortunately this is quite beyond my knowledge. I was hoping someone with the appropriate skill would take an interest.

Thank you very much for your response.

**Comment by Robbbert** [comment]
This work has been done.

Closing.
