### ISSUE TITLE
[NEOGEO] Invalid BIOS

### ISSUE THREAD

**Issue by cd4053** [mamedev/mame#8240]
Windows 10 x64 20H2, hash folder updated.

    mame -version
    0.232 (mame0232-447-ge5d4d10d5f9)

Rom and bios check:

    mame irrmaze -verifyroms
    romset irrmaze [neogeo] is good
    1 romsets found, 1 were OK.

    mame neogeo -verifyroms
    romset neogeo is good
    1 romsets found, 1 were OK.

First try:

    mame irrmaze -window -norc -rompath h:\roms -bios unibios40
    :: invalid BIOS "unibios40", reverting to default
    WARNING: the machine might not run correctly.

Second try, different rom, different BIOS:

    mame kizuna4p -window -norc -rompath h:\roms -bios us
    :: invalid BIOS "us", reverting to default
    WARNING: the machine might not run correctly.

Found this BIOS issue with `irrmaze` and `kizuna4p`, listing the mame roms list for `neogeo.cpp` with `mame neogeo -lb` both are listed, however, both are not listed in `hash\neogeo.xml`.

Other files not listed inside `hash\neogeo.xml` but listed inside `neogeo.cpp`, `mslug2t`, `mvstemp`, `neogeo`, `ng_mv1`, `ng_mv1f`, `ng_mv1fz`, `ng_mv2f`, `ng_mv4f`, `roboarma`, `vliner`, `vliner53`, `vliner54`, `vliner6e`, `vliner7e`.

Possible rom name misspelling in `hash\neogeo.xml`: `roboarmya`    
Possible missing rom file not present in neogeo.cpp but present in `hash\neogeo.xml` file : `totc`

**Comment by Tafoid** [comment]
As I understand things...

- Irritating Maze is a special case requiring a specialized BIOS to function properly with the unique trackball/bar control needed for the game.  You'll also notice that the machine, when you view `-listxml` output, it has no BIOSES listed to select.  This is intentional.
- `kizuna4p`?  Again, another issue where there was a unique PCB board and limited BIOS options shown in  `-listxml` (asia, japan) due to the requirements of allowing up to 4 players (2 teams of 2 players) to play.  Again, intentional.

Why they are not listed in neogeo.xml is because they cannot be run on a home console for the same reasons, specialized inputs and controls needed.  That is what I'd have to guess.  The shortnames you show are largely the board types needed to support the MVS games, with the exception of `roboarma`.

neogeo.xml: `roboarma` - This is likely a mistake than can be corrected.  It is up to the powers that be to decide to change the XML, or change the arcade side to match `roboarmya`.

neogeo.xml `totc` - This appears to be an AES only dump.  I see no way to run it with credits/start system typical of arcade games even if mounted in as neogeo cart:  `mame neogeo -cart1 totc`.

**Comment by cuavas** [comment]
This issue is mostly a collection of misunderstandings:
* The Irritating Maze requires an MV-1B or MV-1C, a SIT interface board (for trackball, lights, etc.), and a BIOS with support for the SIT features.  The BIOS options you’re trying to use are not available on this machine in MAME – only the original Asia BIOS with SIT support is available (we don’t have dumps of any other variants).
* `kizuna4p` is not a different ROM – it shows the alternate title if you connect a NEO-FTC1B JAMMA splitter to the edge connector and SIT header.  Only newer MV-1B and MV-1C BIOS versions support the NEO-FTC1B features.  There’s a separate fixed configuration for it to make it easier for people to use (choose the alternate machine rather than needing to select the correct BIOS and controller).  I need to revisit this one at some point and make sure it doesn’t have the mainboard sound BIOS, since the cost-reduced mainboards lack it.  At any rate, it’s the same cartridge, making a separate software list item for it would be silly.
* If you’re asking why there aren’t software list entries for empty machines that you’re supposed to use to mount software list entries, I don’t know what to say.
* The V-Liner games are video slots based on Neo Geo hardware, they aren’t just cartridges for use with standard Neo Geo setups.
* Treasures of The Caribbean is an AES cartridge never released in arcades – it has appropriate compatibility tags.  Putting it in a fixed JAMMA setup would be silly.
