### ISSUE TITLE
Paris-Dakar is missing dipswitches?

### ISSUE THREAD

**Issue by gspat1** [mamedev/mame#8463]
According to the manual (well, sort of manual) found at this site:

https://www.recreativas.org/paris-dakar-1163-efosa (-note- Spanish)

There should be dipswitch settings for:

credits / coin 1
credits / coin 2
joystick / handlebars
activate / deactivate jump button
demo sounds every ten minutes (?)
difficulty
time per game (freeplay)

Also promotional flyer image from:

https://img.recreativas.org/f/magnet-1-d2696.jpg

Seems to show the name to be Paris-Dakar rather than Paris Dakar (hyphen) even though nothing else shows this.

**Comment by Osso13** [comment]
Hi,are you sure the manual lists dips and not service mode options? It never lists dips and, from what little I understand of Spanish, it says that those settings are adjustable via inputs.

    Il mercoledì 18 agosto 2021, 22:23:56 CEST, gspat1 ***@***.***> ha scritto:  
 
 


According to the manual (well, sort of manual) found at this site:

https://www.recreativas.org/paris-dakar-1163-efosa (-note- Spanish)

There should be dipswitch settings for:

credits / coin 1
credits / coin 2
joystick / handlebars
activate / deactivate jump button
demo sounds every ten minutes (?)
difficulty
time per game (freeplay)

Also promotional flyer image from:

https://img.recreativas.org/f/magnet-1-d2696.jpg

Seems to show the name to be Paris-Dakar rather than Paris Dakar (hyphen) even though nothing else shows this.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by angelosa** [comment]
Those are in service mode yes.
I presume default settings comes from floppy readings (lacking a nvram device in driver), are those sensible enough?

**Comment by gspat1** [comment]
Service mode shows me only input tests? 

even then it only stays in service mode for about 20 - 30 seconds

I'll post a video after I get off work

**Comment by gspat1** [comment]
Ok, I've made a quick video showing what I'm trying to convey..

https://youtu.be/kAIS6x3VJ9A

Just a quick video to point out that there isn't an ability in service mode to change any settings for the game.

Originally, I had thought it was Dip Switch settings, but no, it's probably decided by NVRAM due to settings pre-programmed onto the 3.5" disk the game came on?

Also, the flipping back to attract from service mode wasn't me doing anything intentional, it just did it on it's own?

Hoping this video helps?

**Comment by Osso13** [comment]
I can get all the settings to show up by following this:1) press F2 to enter input test2) press F2 again to continue to settings (the first is credits for coin 1)
2) press button 1 to cycle between the various settings 

    Il venerdì 20 agosto 2021, 01:19:14 CEST, gspat1 ***@***.***> ha scritto:  
 
 


Ok, I've made a quick video showing what I'm trying to convey..

https://youtu.be/kAIS6x3VJ9A

Just a quick video to point out that there isn't an ability in service mode to change any settings for the game.

Originally, I had thought it was Dip Switch settings, but no, it's probably decided by NVRAM due to settings pre-programmed onto the 3.5" disk the game came on?

Also, the flipping back to attract from service mode wasn't me doing anything intentional, it just did it on it's own?

Hoping this video helps?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gspat1** [comment]
ok, that's a first for me... 

never expected to need to press F2 twice!

Thank You!

**Comment by Robbbert** [comment]
Is this issue sorted? Can it be closed?

**Comment by Robbbert** [comment]
Nothing heard. Closing.
