### ISSUE TITLE
Download page simple suggestion

### ISSUE THREAD

**Issue by jumper444** [mamedev/mame#8497]
So i'm a new person (although I know what mame is) going to download the program and get to the download page:

https://www.mamedev.org/release.html

Obviously I know what a 64bit command line binary is (and there is only one choice so 'getting mame' is obvious at this point).

Then there is the download entry under it:
"mame0235lx.zip 	15 MiB 	MAME 0.235 full driver information in XML format."

I know what a driver is. I know what XML is.  Computers aren't new.
But (from a new user's eyes) what is the world is this download? what does it do? who needs it?  why would I require it? what would I do with it? why is it here?  why am I required to stare at it without a description (as one of my first tasks to join the community) and figure it out?

If somebody is coming to this brand new to Mame, then why start by throwing confusing files at them with no explanation?  10 seconds into starting I already don't know what I should be doing on a simple download page.

SUGGESTION: Add a one or two sentences that explain that file, why it is there, when it is needed, and how.  A simple edit in 1 minute that saves thousands from confusion.

Thanks for considering.

(PS:  I'm aware I could get replies of either "well, just download them, unzip them, start reading files inside them and you'll know".... or.... "the explanation of what that file is/does is buried somewhere else on an FAQ or HELP, RTFM".  I have no doubt I can figure out ultimately what to do with the file, but why should it be that difficult?  I hope it is obvious why the most common sense answer is to say what it is right there immediately next to the file.)

**Comment by stilett0** [comment]
In answer to your question, @jumper444 - the "MAME 0.235 full driver information in XML format - mame0235lx.zip" is exactly identical to the output file that someone would get by running "mame.exe -listxml > mame0235.xml" from the command prompt.
https://docs.mamedev.org/commandline/commandline-all.html#mame-commandline-listxml

However. we started adding it as an optional download some years ago.

An XML file is just a text file formatted in a language (XML) that allows for custom tags to provide the data contained within with some structure. https://www.howtogeek.com/357092/what-is-an-xml-file-and-how-do-i-open-one/

This particular MAME XML file, whose information is fully contained within MAME's sourcecode and binary, is often interpreted by MAME helper apps such as frontends (https://docs.mamedev.org/usingmame/frontends.html ) to fully display much of the information contained within MAME about the systems and software it supports, and their configuration.

This MAME XML file is also used by some websites (such as Arcade Database: http://adb.arcadeitalia.net/ or the various emulations available through the browser at the Internet Archive at http://archive.org ).

As such, some of these helper utility developers and websites came to us and asked us for a way to download the current MAME XML file without having themselves or their users generating the file themselves (which as I said above is easily done from the command prompt). 

So that's what we did, and that's what this file is.
