### ISSUE TITLE
No sound in Rampage on the CoCo3

### ISSUE THREAD

**Issue by abcbarryn** [mamedev/mame#8523]
When running Rampage under MAME (or VCC for that matter) there is no sound. On a real CoCo 3, there is a ding as soon as the cartridge loads and asks you to select the monitor type, there is a morse code sound that plays when starting a new city, and bombs, bullets, and punching noises in the game.

**Comment by Tafoid** [comment]
This has likely never worked at all in MESS or MAME.  I did notice there is a FPGA core (closed sources, of course) for COCO3 which claims to have this problem fixed.  Too bad the solution never showed up on our shores.

I did a bit of digging I found this link to some notes from the core author regarding possibly coaxing audio from Rampage.  Maybe this could be helpful to the right skilled person to get things working.

https://m.facebook.com/groups/mistercoco/permalink/1010725475797707/?m_entstream_source=group&anchor_composer=false

**Comment by abcbarryn** [comment]
Why was this closed? It's not fixed.

**Comment by Tafoid** [comment]
Just checking sounds and I hear all the dings and punches/bullets/crashes here on the released Windows binary for MAME 0.237 and current Git.  I tried to load it via softlist and as a picker item -cart (location of rampage.zip) and both work.  Unsure why you are still having issues.  This issue was closed here as it was more appropriate for MAMETESTERS.  Git Issues is reserved more for current active source changes that are not present or detected in the most recently released build or source package.
