### ISSUE TITLE
Incorrect offset in msx1_cart.xml

### ISSUE THREAD

**Issue by mnadareski** [mamedev/mame#874]
In the software list, there is the following entry:

	<software name="begbasic">
		<description>Beginner's BASIC I (Euro?)</description>
		<year>1985</year>
		<publisher>Casio</publisher>
		<part name="cart" interface="msx_cart">
			<dataarea name="rom" size="65536">
				<rom name="casio_basic.rom" size="32768" crc="2181a21d" sha1="c48a68db822d9bded56ee1df55d18b81fbe135b7" offset="0x400x40000" />
			</dataarea>
		</part>
	</software>`

The offset does not appear to be a proper hex value. Instead, it should be 0x40000.

**Comment by LnmVolbo** [comment]
Well spotted, but you may have put one too many zeros.

The enclosing dataarea size is 65536 (0x10000), so the correct offset may be 0x4000, rather than 0x40000.

Only one item on this softlist has an offset of 0x40000, and it's enclosing dataarea size is 524288 (0x80000).

There are numerous other offsets of 0x4000 on this softlist, and all their enclosing dataarea sizes are 65536.

**Comment by rb6502** [comment]
Please verify that the software was fixed by Robbbert's change so we can close this.

**Comment by rb6502** [comment]
*bump* mnadareski, can you please verify that Robbbert's change fixed your problem?

**Comment by Robbbert** [comment]
Nothing heard, closing.
