### ISSUE TITLE
feature request: run unknown romset

### ISSUE THREAD

**Issue by kirbypinkgamer** [mamedev/mame#8811]
Hi

I would like to request a command line feature for mame considering the arcade game list.

In order to run a romset not present in mame game list (for example a rom from a derived mame project, a completely newly dumped rom or a homebrew rom, ...) I would like to request a feature to run unknown roms.
So no crc checking is done of course.

Mame -unknownrom -drivername romset.zip

Mame tries to run the rom using the chosen driver (at own risk). It should work with similar romsets, or new dumps etc when the game is using the same driver (same family of game).

**Comment by kirbypinkgamer** [comment]
A good example could be running hbmame roms in 'normal' mame.
The romsets will just work fine without any crc checking on the rom files if you select the correct driver.

**Comment by rb6502** [comment]
MAME already will load and run a game with mismatching CRCs from the command line, so if you have a favorite HBMAME game you can replace the "normal" version with it and regular MAME will run it.  It is not feasible to load arbitrary sets/games because there is no way to know the ROM loading configuration; one driver can have over a dozen configurations.

**Comment by angelosa** [comment]
The nearest thing an user can do to run “loose / homebrew” BIOSes is to overwrite the rompath with an override folder/zip in it, mimicking the ROM structure (names and lengths) of the parent origin.

Not sure how much better an alternative can possibly be, if you handle above with a script you can also handle stdout/stderr and ignore the crc/sha1 errors anyway.
