### ISSUE TITLE
"history" folder created each time MAME runs

### ISSUE THREAD

**Issue by jotego** [mamedev/mame#8815]
I've been puzzled for a long time looking for the responsible of folders called history appearing in my linux workstation. I finally found the culprit. MAME seems to create a **history** folder with a **history.db** file inside whenever it runs and in the folder where it has been called. If you trigger MAME from the terminal, this means that you can get these folders anywhere.

I think this behaviour should change as it pollutes the user's drive. One suggestion is to create that history folder in  ~/.mame instead.

**Comment by cuavas** [comment]
Well, it won’t create that file if you don’t enable the data plugin, so you can disable the data plugin or disable plugins altogether to stop it doing anything.  (It’s enabled by default because lots of people like to use history.xml, mameinfo.dat, command.dat, etc.)

If you keep the plugin enabled, you can control the place it creates that file by setting the first path in the `historypath` setting in ui.ini to a location that suits you better.  You can also control the setting from the internal UI (it’s called “DATs” there because MAME isn’t great at consistency).

Now there’s an argument to be made that the file shouldn’t be created in that directory, since it’s a source location, and the plugin should store its housekeeping data in the plugin data folder (set using the poorly-named `homepath` option in mame.ini, defaults to working directory), but that’s a question for a different day.

MAME defaults to searching for and creating folders relative to the working directory to make life simple for developers.  We often have multiple builds of MAME that may be broken in different ways.  Using the working directory by default means each build can be somewhat self-contained.  However, on Linux, MAME should look for ~/.mame/mame.ini and ~/.mame/ui.ini so you can put your path configuration there.

**Comment by jotego** [comment]
Thank you very much for the explanation. It was very informative.

**Comment by skierpage** [comment]
This issue should not be closed. By default `mame` 0.243 on Fedora 35 creates `history/history.db` in whatever directory you start it in. (!!) This causes needless confusion, see [here](https://www.linuxquestions.org/questions/linux-general-1/what%27s-the-%27history-db%27-file-that-keeps-appearing-in-my-home-folder-4175691468/), [here](https://www.reddit.com/r/linuxquestions/comments/ljqspd/what_is_the_historydb_file_in_history/), [here](https://groups.google.com/g/linux.debian.user/c/-_NR_0EWn8I/m/hlX-T-N_CgAJ),...

>  Using the working directory by default means each build can be somewhat self-contained.

I appreciate the work y'all put into MAME, but that's very poor default behavior! After working hard I take a break by starting `mame`, and `locate /history.db` revealed I have 7 of these meaninglessly named paths in random work directories. Telling 50 MAME developers how to keep builds separate is a lot easier than telling all your end users to add something to `ui.ini`.

The standardization of user data was solved on UNIX-like systems years ago. From https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html :
> $XDG_DATA_HOME defines the base directory relative to which user-specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.

Create `mame/history/history.db` in there and users won't be confused, and developers can set XDG_DATA_HOME to any directory before starting mame.

**Comment by rb6502** [comment]
MAME on Linux as we ship it will look for mame.ini in ~/.mame/, specifically to prevent things like this.  However, I gather this violates everyone's guidelines in some way because none of the distro packagers leave that setup intact.  Basically, if you're installing from RPM/DEB, you are not running what we ship and you keep all the pieces if it breaks.

**Comment by skierpage** [comment]
> MAME on Linux as we ship it will look for mame.ini in ~/.mame/, specifically to prevent things like this. However, I gather this violates everyone's guidelines in some way because none of the distro packagers leave that setup intact. Basically, if you're installing from RPM/DEB, you are not running what we ship and you keep all the pieces if it breaks.

Fedora looks for `~/.mame/ini/ui.ini`. But the default in ui.ini set, I think, by [src/frontend/mame/ui/moptions.cpp](https://github.com/mamedev/mame/blob/master/src/frontend/mame/ui/moptions.cpp#L24) is
```
historypath               history;dats;.
```
which leads to the clearly wrong behavior of creating yet another `history/history.db` in whatever the current working directory happens to be. If I remove `~/.mame/ini/ui.ini`, MAME continues to do the same (and recreates `~/.mame/ini/ui.ini` with the same `historypath` entry). So unless I'm missing something, this behavior is unrelated to the path for .ini files or distro changes, it is baked into MAME (intentionally, @cuavas suggests).

FWIW I fixed it by changing the line to
```
historypath               $HOME/.mame/history;dats;.
```
, but letting users stumble over random files with no apparent connection to MAME all over their filesystem and then making them hunt for and apply this fix is inappropriate. I don't know if changing the line in `moptions.cpp` to
```.cpp
     { OPTION_HISTORY_PATH,           "$HOME/.mame/history;dats;.",     ...
```
would work, if so it seems an easier fix than adopting the more flexible XDG directory standard, and developers could always change it back in ui.ini if they want the unexpected current behavior. Cheers.

**Comment by cuavas** [comment]
The trouble is, that’s going to break the “portable” way a lot of people run MAME, particularly developers.

Historically, MAME has been designed to run from a self-contained directory containing the binary, matching support files, and other data files.  This is still the way most users run MAME on Windows – they extract the binary distribution archive, then run MAME by double-clicking it in Windows Explorer, which results in the working directory being set to the folder containing the executable.  It’s also the way developers typically run MAME during development – you clone/checkout the source, compile, and then run MAME from the source directory.

Double-clicking an executable on Linux or macOS runs it with the working directory set to the user’s home directory.  Historically, this wasn’t a problem, as MAME didn’t have an internal UI for selecting systems or software to run.  If you double-clicked it, MAME would just print a message telling you no system was selected and exit (leading to the, “Running MAME just makes a DOS window appear and close after a second!” complaints).  Linux/macOS users were forced to run MAME from the command line, so they’d have the working directory set properly, or they’d use a front-end like QMC2, MMiX or something that took care of it for them.

This approach gives a few benefits:
* It makes MAME the setup mostly self-contained.  In its default configuration, MAME won’t do much to pollute your filesystem outside the working directory.  (The exception is that on macOS or other UNIX-like operating systems it saves `mame.ini` and `ui.ini` in `~/Library/Application Support/mame` or `~/.mame`, respectively.)
* For developers or testers who need to run multiple versions of MAME, it makes it easier to avoid interference between environments, or inadvertently destroying valuable data.  For example configuration files occasionally change format, testing often requires deleting or otherwise manipulating non-volatile RAM files, and so on.  If MAME didn’t run in self-contained mode by default, developers and testers would need to manually take steps to ensure each version of MAME they runs in a “clean” environment.  I dread the developer rage that would ensue if they forgot to set the `inipath` option for an old version of MAME they were testing, and it damaged their precious NVRAM containing high-scores, their painstakingly created input macros and autofire buttons, and so on.
* It makes it easy to have a MAME setup on removable media that you can use with multiple machines.  Compact, high-capacity USB2 hard disks make this more popular than you might expect.

Changing this would also break expectations, and that’s something I try to do infrequently.  There’s a reason I try to group workflow-breaking changes when possible.  It’s better to have substantial breaking changes that happen occasionally rather than small breaking changes that happen constantly.

Now I’m willing to admit that there *are* some issues with the way plugin data is handled at the moment, particularly with the data plugin:
* The option that controls the plugin data location, `homepath`, is named incredibly poorly.  The name does not reflect what it does.  I’ll take the blame for this – I should have been paying more attention when it was added and ensured it was renamed before it made it into a release.
* Using the working directory as the default `homepath` location isn’t a great idea.  It really should at least default to a subdirectory so the plugin data is collected together and doesn’t have the potential for clashes between plugin names and other files/folders in the working directory.
* The data plugin should probably be saving its cache to the plugin data folder rather than the so-called history folder.  The history folder is for inputs, and it would make sense to be able to use a read-only location for it (e.g. to share it between machines/users).

Changing the name of the `homepath` option is not something to do lightly.  It affects all plugins that need to save data directly, including those not in the mainline repository (plugins look up options using name strings).  If we’re going to change it, we need to make sure we know we’ve made up our minds about what it should be called.

Changing the default for the `homepath` option is also something that I’d want a pretty strong consensus on before pushing it out.  We *could* change it to something like `~/.mame/plugin-data` on Linux and `~/Application Support/mame/plugin/data` on macOS.  The disadvantage of this is that doing so would mean developers/testers would potentially nuke their valuable plugin data (e.g. input macros, autofire buttons, high scores, play time statistics) when testing an unstable version of MAME, or if they introduced a bug while working on the Lua API or something.  Developer rage is not something I want to trigger unnecessarily.

I’m in half a mind to just go ahead and change to the data plugin to save its cache in the plugin data directory.  The only problem with doing that is the complaint will just change to a `data` folder being created in your home folder rather than a `history` folder.

**Comment by sairuk** [comment]
It is completely reasonable for mame to operate using relative pathing. If I run mame packaged with the absolute path from a path i don't have write perms too, every relative path from ui.ini will fail, this is acceptable.

being completely upfront I've never bothered to look at the plugin side of mame until now. 

if I run mame with the absolute path from the root dir (`/`), homepath set to the default `.`
```
$ /usr/games/mame  
Unable to create history.db
Unable to create history.db
Unable to create history.db
Error saving hiscore plugin settings: error opening file "./hiscore/plugin.cfg" for writing
```
I would expect the end user to configure the application correctly i.e the user or package maintainer

but in the case of `historypath` it seems `homepath` settings are ignored whereas for a plugin like hiscore they are honored

```
$ /usr/games/mame -showconfig | grep homepath
homepath                  $HOME/.mame
```

running mame with absolute path but homepath set
```
$ /usr/games/mame 
Unable to create history.db
Unable to create history.db
Unable to create history.db
```

hiscore strace
```
$ grep hiscore ~/mame.log 
stat("/usr/share/games/mame/plugins/data/data_hiscore.lua", {st_mode=S_IFREG|0644, st_size=41433, ...}) = 0
stat("/usr/share/games/mame/plugins/hiscore", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/usr/share/games/mame/plugins/hiscore", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 5
stat("/usr/share/games/mame/plugins/hiscore/plugin.json", {st_mode=S_IFREG|0644, st_size=167, ...}) = 0
openat(AT_FDCWD, "/usr/share/games/mame/plugins/hiscore/plugin.json", O_RDONLY) = 6
stat("/usr/share/games/mame/plugins/hiscore/init.lua", {st_mode=S_IFREG|0644, st_size=10068, ...}) = 0
stat("/usr/share/games/mame/plugins/hiscore/sort_hiscore.lua", {st_mode=S_IFREG|0644, st_size=4447, ...}) = 0
stat("/usr/share/games/mame/plugins/hiscore/hiscore.dat", {st_mode=S_IFREG|0644, st_size=308207, ...}) = 0
stat("/usr/share/games/mame/plugins/hiscore/..", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/usr/share/games/mame/plugins/hiscore/.", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/usr/share/games/mame/plugins/hiscore.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/games/mame/plugins/hiscore/init.lua", O_RDONLY) = 5
openat(AT_FDCWD, "/usr/share/games/mame/plugins/hiscore/init.lua", O_RDONLY) = 5
read(5, "-- hiscore.lua\n-- by borgar@borg"..., 4096) = 4096
openat(AT_FDCWD, "/usr/share/games/mame/plugins/data/data_hiscore.lua", O_RDONLY) = 20
openat(AT_FDCWD, "/usr/share/games/mame/plugins/data/data_hiscore.lua", O_RDONLY) = 20
openat(AT_FDCWD, "/home/sairuk/.mame/hiscore/plugin.cfg", O_RDONLY) = 19
openat(AT_FDCWD, "hiscore.dat", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/games/mame/plugins/hiscore/hiscore.dat", O_RDONLY) = 19
read(19, "**\n;*** for a bigger hiscore tab"..., 4096) = 4096
read(19, "n) - For the hiscore to display "..., 4096) = 4096
stat("/home/sairuk/.mame/hiscore", {st_mode=S_IFDIR|0750, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/home/sairuk/.mame/hiscore/plugin.cfg", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 19

```

history strace
```
stat("/usr/share/games/mame/plugins/data/data_history.lua", {st_mode=S_IFREG|0644, st_size=4339, ...}) = 0
lstat("history/history.db", 0x7fff809cd370) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "//history/history.db", O_RDWR|O_CREAT|O_NOFOLLOW|O_CLOEXEC, 0644) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "//history/history.db", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
mkdir("history", 0775)                  = -1 EACCES (Permission denied)
lstat("history/history.db", 0x7fff809cd370) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "//history/history.db", O_RDWR|O_CREAT|O_NOFOLLOW|O_CLOEXEC, 0644) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "//history/history.db", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
write(2, "Unable to create history.db", 27) = 27
openat(AT_FDCWD, "/usr/share/games/mame/plugins/data/data_history.lua", O_RDONLY) = 20
openat(AT_FDCWD, "/usr/share/games/mame/plugins/data/data_history.lua", O_RDONLY) = 20
lstat("history/history.db", 0x7fff809cd4d0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "//history/history.db", O_RDWR|O_CREAT|O_NOFOLLOW|O_CLOEXEC, 0644) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "//history/history.db", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
mkdir("history", 0775)                  = -1 EACCES (Permission denied)
lstat("history/history.db", 0x7fff809cd4d0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "//history/history.db", O_RDWR|O_CREAT|O_NOFOLLOW|O_CLOEXEC, 0644) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "//history/history.db", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
write(2, "Unable to create history.db", 27) = 27
lstat("history/history.db", 0x7fff809cd4d0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "//history/history.db", O_RDWR|O_CREAT|O_NOFOLLOW|O_CLOEXEC, 0644) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "//history/history.db", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
mkdir("history", 0775)                  = -1 EACCES (Permission denied)
lstat("history/history.db", 0x7fff809cd4d0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "//history/history.db", O_RDWR|O_CREAT|O_NOFOLLOW|O_CLOEXEC, 0644) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "//history/history.db", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
write(2, "Unable to create history.db", 27) = 27
```

personally to the `homepath` issue I think the defaults are fine, it's either a packaging or doco issue, package maintainers can configure a `homepath` to `$HOME/.mame` and leave the project defaults alone. 

The creation of the history directory however needs to be standardised against other plugins though and should honor `homepath` which it doesn't appear to do at the moment

should this be handled in `database.lua` having it honor `homepath` initially?

https://github.com/mamedev/mame/blob/d775a2731d7be00fe53932c43cb2321769ef1989/plugins/data/database.lua#L12

**Comment by cuavas** [comment]
I already explained this - the data plugin is badly behaved. The `historypath` option specifies the location to read these miscellaneous files like command.dat, history.xml, etc. but the data plugin also uses this as a location for its cache database.

There are several things to change here, but they should be all changed at once after reaching consensus to avoid a series of workflow-breaking changes:
* Rename `homepayh` to make it descriptive
* Change default plugin data directory to at least keep stuff grouped in a single folder
* Make data plugin defer creating its cache database until it has something to put in it (actually this one can be done independently)
* Make data plugin honour the plugin data directory option for the location to store its cache database

**Comment by jotego** [comment]
I'm glad this conversation came to life again. Recently, I installed MAME on a MacOS and found the same problem. I came  to this issue and read the solution I got back then. Only to find that, for some reason, it didn't work on the MacOS installation. I am just careful to always start it from ~/.mame at the moment. 

It would be nice if MAME at least produced a line on the screen saying that it created that "history" folder, so at least the user is not left wondering where that folder came from.

**Comment by cuavas** [comment]
> Only to find that, for some reason, it didn't work on the MacOS installation.

That's because the location it searches on macOS is `~/Library/Application Support/mame` rather than `~/.mame` to better meet user expectations for macOS applications.

**Comment by cuavas** [comment]
> There are several things to change here, but they should be all changed at once after reaching consensus to avoid a series of workflow-breaking changes:
> 
> * Rename `homepath` to make it descriptive
> * Change default plugin data directory to at least keep stuff grouped in a single folder
> * Make data plugin defer creating its cache database until it has something to put in it (actually this one can be done independently)
> * Make data plugin honour the plugin data directory option for the location to store its cache database

923ef2c25db75ccb6a6d747304fc9c79ef454a46 implements the latter two of these:
* The data plugin will now defer creating its cache database until it has something to put in it.  If you don’t have history.xml, mameinfo.dat, etc. in a path where MAME can find it, the history.db file won’t be created.
* The data plugin now honours the `homepath` option, so when the history.db file is created, it will be put inside a folder called “data” in the folder configured using the `homepath` option (which still defaults to the working directory).

This should at least solve the annoyance of the cache database being created when there’s nothing to put in it.

**Comment by jshbrntt** [comment]
Same issue with a `logs` directory that is created in the current working directory wherever you run `mame` from CLI.

**Comment by skierpage** [comment]
> Same issue with a `logs` directory that is created in the current working directory wherever you run `mame` from CLI.

FWIW that doesn't happen to me with the mame 0.255 rpm package on Fedora 38. I ran `strace mame` and it doesn't open or stat any path containg `log`.

> Even with `log` disabled in my `~/.mame/mame.ini` file.

My mame.ini is similar except the debugscript line has no value. I changed it to 0, nothing changed still no `logs`. YMMV :wink:
