### ISSUE TITLE
CHD file size in xml

### ISSUE THREAD

**Issue by oldcodewizard** [mamedev/mame#8906]
Hello

I'm trying to make a ROM manager. The size of a rom file is written in both -listxml and -listsoftware.
However for Chd files there is NO file size written anywhere.

I want to check the file size of chd files too in my rom manager. Would it please be possible to add the file size, exactly the same as for rom files?

**Comment by cuavas** [comment]
The size for ROM files is there because it's part of the load command. CHDs aren't loaded into memory (they're accessed as block storage), so the size isn't needed. Really, you should be reading the CHD header and checking the digest, like MAME does. (If a size was required, it would be the data size, not the file size. The for size can vary for the same data size due to compression.)

**Comment by oldcodewizard** [comment]
Where czn I find information about chd header? I'm not a c++ coder so I can't really check mame source code.

Is there a data size in the header or only a checksum on the data?

**Comment by cuavas** [comment]
Well, if you don’t want to read C++, there’s a JavaScript sample that reads the signature, version and SHA1 digest from the CHD header: https://github.com/mamedev/mame/blob/mame0238/scripts/minimaws/lib/assets/romident.js#L12

(This kind of thing is easier to read when it’s C++ than JavaScript to be honest, due to JavaScripts aversion to binary integers.)

The C++ code for reading CHD headers is pretty straightforward:
* v3: https://github.com/mamedev/mame/blob/mame0238/src/lib/util/chd.cpp#L1768
* v4: https://github.com/mamedev/mame/blob/mame0238/src/lib/util/chd.cpp#L1831
* v5: https://github.com/mamedev/mame/blob/mame0238/src/lib/util/chd.cpp#L1891

**Comment by oldcodewizard** [comment]
How to know what header structure to use? Where is version stored?

So if I understand correctly, the chd's to be downloaded 'somewhere' can be version 3, 4 or 5? Or is everything converted to 5 ?

**Comment by cuavas** [comment]
You need to read the version field from the header.  Both the JavaScript and C++ show you how to do that.  I’m sorry, but writing a ROM manager requires programming.  This is not a support forum.  If you want programming help, take it to an appropriate venue.
