### ISSUE TITLE
Famicom Arkanoid 2 player Paddle support (feature request)

### ISSUE THREAD

**Issue by riggles1** [mamedev/mame#8920]
MAME 0.238, on the actual Famicom, the Vaus Arkanoid Dial hooks up to the expansion port and daisy-chains in order for 2 players to play.
In MAME the only option you have is Vaus hooked up to the P2 port, no way for two player Arkanoid VS. 
P1 has to be a controller in order to select the VS. mode with the select button.

A solution to this would be introducing an expansion port device (instead of only having P1 and P2 devices), allowing P2 to have a Vaus, and Exp. to have a Vaus.

**Comment by 0kmg** [comment]
@riggles1 It seems this feature is used only by Arkanoid 2 and that game is Japan-only. The NES and Famicom peripherals are not generally hardware compatible, so if this feature gets added it will only be possible to use it through the Famicom machines in MAME, not the NES ones. (Try running `mame -listslots famicom` and you'll see there's quite a few things on the expansion port unique to the FC.)

A further note (to self?) in order to fulfill this feature request: based on preliminary reading it looks like the Arkanoid paddles sold with the two Japanese games in the series are slightly different. Ark 1 paddle does NOT have the daisy-chainable extra expansion port. Ark 2 paddle does. The important difference, however, is the range of values for the Ark 2 paddle seems to be slightly wider. You can see this in action in MAME, which uses the Ark 1 paddle ranges—run `mame famicom -exp vaus arknoid2` and it's clear that you can't move the ship all the way to the left

**Comment by 0kmg** [comment]
@riggles1 Merry holidays! Looks like the next release will have support for two paddles in VS mode. It's probably easiest to select things in **Slot Devices** in the menu. Command line syntax for subslots is a bit unwieldy, but if you must it's: `mame famicom arknoid2 -exp vaus -exp:vaus:subexp vaus`. Either way you'll likely need to configure inputs.

**Comment by riggles1** [comment]
Thank you! Merry Holidays from me as well :D 
Gonna be really cool to try the two player mode.
