### ISSUE TITLE
Integer scaling, aspect ratio and artwork issues

### ISSUE THREAD

**Issue by cd4053** [mamedev/mame#9115]
OS: `Windows 10 21H1` / `Debian x64`
mame: `0.239 (mame0239-103-g061b2e1d952)`
command: ` mame sf2 -norc -window -override_artwork lines -sound none -skip_gameinfo -noues -sx 3`
artwork: [lines.zip](https://github.com/mamedev/mame/files/7833823/lines.zip)

**Issue 1**
Set Non-Integer Scaling to `X or Y (Auto)`, the screen shrinks.
![sf2-small](https://user-images.githubusercontent.com/80734530/148656619-55a9f828-3d67-4a69-a7d7-743855b9e27d.png)

**Issue 2**
Disable "Maintain Aspect Ratio" and "Non-Integer Scaling", we have a zoom.
![sf2-small-zoom](https://user-images.githubusercontent.com/80734530/148656712-6e6a0139-d9ed-4910-a8ee-5253d0617e68.png)

**Issue 3**
Cycle "Non-Integer Scaling" to "Y Only", we have a bigger zoom.
![image](https://user-images.githubusercontent.com/80734530/148656739-3cf73914-4045-42db-95d1-c25216a1e264.png)

**Issue 4**
Turn "Non-Integer Scaling" **off** and "Maintain Aspect Ratio" **on**, even bigger zoom.
![image](https://user-images.githubusercontent.com/80734530/148656772-177bffcb-871e-48d6-a462-900afae42344.png)

**Issue 5**
Turn "Maintain Aspect Ratio" **on** and "Non-Integer Scaling" **off**, the window now has an expected size, turn "Maintain Aspect Ratio" **off** and cycle the options at "Non-Integer Scaling", it does nothing. 

**Issue 6**
Turn "Maintain Aspect Ratio" **on**, cycle the options at "Non-Integer Scaling" to see the window change sizes, this behavior changes with SDL builds.

**Issue 7**
Press Alt+Enter to enter full screen and select the "screen lines" artwork, setting "Non-Integer Scaling" **on** or **off** keep the black lines aligned with the rest of the lines, changing the "Non-Integer Scaling" to `X/Y Only` or `X or Y Auto` you see the lines shifting one pixel in X or Y axis.

**Issue 8**
You can see an even bigger line misalignment if you press **F12** to screenshot the artwork, regardless if you are using "Non-Integer Scaling"/"Maintain Aspect Ratio" or not. 
![0000](https://user-images.githubusercontent.com/80734530/148657238-993dc021-6052-4818-8ba1-2e961bb0b686.png)

**Comment by ICEknigh7** [comment]
This doesn't happen to me on Windows 10.

**Comment by cuavas** [comment]
Look, the more this is changed, the more issues it seems to create.  Are these options becoming more trouble to maintain than they’re worth?

**Comment by antonioginer** [comment]
The op is forcing -sx 3, that's the issue.

**Comment by antonioginer** [comment]
> Look, the more this is changed, the more issues it seems to create. Are these options becoming more trouble to maintain than they’re worth?

Hi Vas,

I think these options are very much needed, and some devs have said they find them useful for developing as well. I have tested everything thoroughly, again, and my scaling code, with latest updates, works as expected in all testing cases.

However, the issues reported here are caused by how the window manager code interacts with the visible area rectangle, that's reported by the rendering code. Let's say, the window manager code wasn't designed to deal with some special cases that were introduced by these new scaling modes. Basically, these cases are 3:

- Force integer scale factors (`-sx`, `-sy`) can result in a situation where the computed dimensions of a minimized vs a maximized window are the same (it makes sense since you're forcing those!). This confuses the window code, activating both `m_isminimized` and `m_ismaximized` at the same time. Since the minimize code is called first, this causes **issue 1**, when the user starts MAME maximized but cycles to a scale mode that triggers the situation explained, and sends the window to minimized dimensions.

- Forced integer scale factors (`-sx`, `-sy`) can also lead to a minimized rectangle larger than what `get_min_bounds` returns (**issues 2 & 3**). This happens with `-nokeepaspect`, because `constrain_to_aspect_ratio` would catch it otherwise.

- Now, `compute_visible_area` can return a rectangle that's bigger than the target size. This may happen either when `-intoverscan` is enabled, or when the user manually specifies integer scale factors (`-sx`, `-sy`), which can easily result in a rectangle of larger dimensions than the window. The actual problem is this can result in a maximized window that's larger than the screen, even hiding the caption bar as the window centering code returns negative coordinates.

**Issues 4 & 5** are caused by the keep aspect UI control not triggering a window resize. For coherence, it should be wired with the rest of scale and layout settings that cause a window resize. Some think this is an annoying behavior and prefer the SDL way, where the window borders are only updated by user's input. This inconsistency may be confusing (**issue 6**).

**Issues 7 & 8** are totally unrelated to the scaling code, and probably have to do with rounding issues on the artwork layout.

These issues aren't new, or at least aren't caused by my PR, which indeed fixes some real previous issues. If anything, my PR has exposed these situations, by attempting to resize the window when switching between scaling modes (in coherence with the Windows build).

Later I'll create a PR that hopefully fixes all reported issues. Please consider the fact that this window manager code isn't the easiest to deal with.

**Comment by john-iv** [comment]
@antonioginer thank you for your continued work on these stretching options.  

I have a question about the current implementation of -autostretchxy and its expected use.  I have a 1440 monitor (2560x1440).  When I play pacman (mame.exe pacman -autostretchxy) it appears to choose to key on the Y axis when I observe it in the [tab] video options.  However, if I then change to 'X only axis' in video options the picture is actually larger and takes up more of the screen which is pleasing.

Is this expected behaviour for -autostretchxy?  Should it be trying to find the largest 'fittable' implementation which in this case would be keying on the X only axis?  Or should it key on the axis simply based on being a vertical vs horizontal game.  Same thing happens in dkong and a few others.  Thanks -

**Comment by antonioginer** [comment]
@john-iv, thanks for your comments.

Yes, -autostretchxy always tries to apply fractional stretching on the direction of the scanlines (assuming the source is a raster screen), and integer scaling on the other. This is done to produce evenly spaced scanlines, without scaling artifacts. It won't always result in the largest fittable rectangle, because that's not its goal.

You may try -intoverscan, it can help in some cases were the picture doesn't fit just for a little bit. You'll get a bigger picture at the cost of some cropping. 

Scaling artifacts shouldn't matter so much on high resolution screens, although they become obvious on lower resolution panels (laptops mainly).

**Comment by cd4053** [comment]
Thank you @rb6502, looks good from here.
