### ISSUE TITLE
request: add CHIP-8 emulator to MAME

### ISSUE THREAD

**Issue by pygamedev** [mamedev/mame#9246]
Hi

I would like to request to add CHIP-8 emulator to MAME. It's not hardware being emulated then but an interpreted language.
It's part of gaming history so it should be preserved too in MAME. 
A software list chip8.xml could be added and a new driver chip8.cpp.

Below the history, tech docs, ROMs (including a test ROM for all opcodes!) and more goodies!

CHIP-8 was created by RCA engineer Joe Weisbecker in 1977 for the COSMAC VIP microcomputer. It was intended as a simpler way to make small programs and games for the computer. Instead of using machine language for the VIP’s CDP1802 processor, you could type in simple hexadecimal instructions (with the VIP’s hex keypad) that resembled machine code, but which was actually interpreted on the fly by a small program.

CHIP-8 soon spread to other computers, like the Finnish Telmac 1800, the Australian DREAM 6800, ETI-660 and MicroBee, and the Canadian ACE VDU. By 1984 the support for CHIP-8 petered out. However, in 1990 it had a renaissance on the HP48 graphing calculators with CHIP-48 and the now-famous SUPER-CHIP extension with higher resolution.

http://devernay.free.fr/hacks/chip8/C8TECH10.HTM

https://chip-8.github.io/links/

https://tobiasvl.github.io/blog/write-a-chip-8-emulator/

**Comment by Robbbert** [comment]
There's already several chip8 computers in MAME: Various RCA models, Dream 6800, ETI660 and more.
A software list already exists.

You would need to write the code and submit a PR if you want this to progress.

**Comment by cuavas** [comment]
CHIP8 was an early example of a hardware-independent virtual machine, in the same vein as AS/400’s TIMI, the Java runtime, or the .NET CLR.  It isn’t MAME’s purpose to emulate these kinds of virtual machines directly.  As @Robbbert already noted, MAME already emulates several computers with CHIP-8 runtimes.  You could build a CHIP-8 emulator using MAME’s framework, but it doesn’t really belong in MAME itself.

**Comment by pygamedev** [comment]
> CHIP8 was an early example of a hardware-independent virtual machine, in the same vein as AS/400’s TIMI, the Java runtime, or the .NET CLR. It isn’t MAME’s purpose to emulate these kinds of virtual machines directly. As @Robbbert already noted, MAME already emulates several computers with CHIP-8 runtimes. You could build a CHIP-8 emulator using MAME’s framework, but it doesn’t really belong in MAME itself.

What exactly do you mean?
You only need to emulate the Chip-8 virtual machine to run a chip-8 ROM.
I don't know why you emulate the hardware itself, since the GOAL of a virtual machine is to be hardware independent.
So it's useless to emulate all the hardware it runs on, because the ROMs only run on top of the interpreted chip-8 language...

**Comment by cuavas** [comment]
You’re misunderstanding the purpose of MAME.  With very limited exceptions, MAME does not emulate virtual machines, it documents and emulates real machines and the software that ran on them.

In reality, the behaviour of a CHIP-8 system depends on the real machine it ran on:
* The native interpreter code was often accessible to the CHIP-8 software.
* Various features were implemented as calls to native code.
* CHIP-8 software could include native functions and call them.
* The instruction throughput and latency is dependent on the interpreter and host hardware.

There are also behavioural differences between implementations of CHIP-8.  The CHIP-48 interpreter that resulted in CHIP-8 regaining attention differed from the original COSMAC VIP in significant ways, and a lot of modern CHIP-8 software assumes CHIP-48 behaviour.

MAME emulates systems that included or supported CHIP-8 environments, ranging from the COSMAC VIP where it all began, to the HP-48 that revived it with CHIP-48, to PC systems, allowing you to experience CHIP-8 software in context.

**Comment by pygamedev** [comment]
1) it's useless to emulate the hardware that runs a virtual machine. Google for chip-8 emulator in ANY language, you won't find any hardware emulation. Only the virtual machine is emulated

2) chip-8 and super chip-8 require 2 diferent emulators. Hardware INDEPENDENT. It has nothing to do with the hardware. The second is an update of the first and therefore not compatible

3) please give me a rom example to proof your first 3 points. Until you give this to me and indicate a so called 'native code' inside this rop, unaccessible of course because of the virtual machine, those things belong in fairy tale land...
THE CHIP-8 opcodes only do things on the virtual machine registers, stack, ... You can find the opcodes online.

4) the last point is correct. Again a virtual machine has nothing to do with the hardware it runs on. A chip-8 ROM doesn't care and also don't 'know' on what hardware it runs. Every software is dependent on the host hardware, also mame.
You can't do anything about this. It has nothing to do with emulating the opcodes in a chip-8 rom.


You are not capable of leading a project as mame because of the nonsense you say.

And finally mame preserves game history. Chip-8 is a BIG part of it. It belongs certainly in mame. Game history must not be split in real hardware or virtual machines to decide what's in or not. Mame in fact is a virtual machine on itself...

**Comment by pygamedev** [comment]
Chip-8 is actually SO important because of the enormous time span I took and pickup up later again by much more modern hardware.
So it would be a crime not to include chip-8 and super chip-8 into MAME.
I guess you like to commit crimes against the preservation of gaming history...

Closed. I won't even read your answer because you can't proof the first 3 points you say.

**Comment by ajrhacker** [comment]
MAME already does emulate hardware purposely designed to run specific virtual machines. For instance, the mk1forth driver emulates a simple homebrew TTL CPU (http://www.aholme.co.uk/Mk1/Architecture.htm) that runs a FORTH interpreter which is itself written in bytecode.

**Comment by cuavas** [comment]
CHIP-8 was written by Joseph Weisbecker to provide a simplified environment for users to write their own games on the COSMAC VIP.  Many implementation details and characteristics of the original host system are exposed:
* The somewhat unusual hexadecimal keypad layout used by CHIP-8 (telephone digit layout with A and B on opposite sides of 0) is based on the data entry keypad of the COSMAC VIP.
* The CHIP-8 interpreter on the VIP occupied the first 512 bytes of the address space.  This is why CHIP-8 programs start at location 0x200, because the interpreter occupies the space below that.  CHIP-8 programs can access the interpreter code by reading locations below 0x200.
* The CHIP-8 interpreter on the VIP used locations 0xF00-0xFFF for display and 0xEA0-0xEFF for interpreter state, leading to locations from 0xEA0 onward being reserved.
* The **0x8xyo** operations were implemented by translating to CDP1802 instructions.  The undocumented **0x8xy3** (exclusive or), **0x8xy6** (right shift), **0x8xy7** (subtract from) and **0x8xyE** (right shift) were fortuitous emergent behaviour created by the implementation.
* The original CHIP-8 interpreter includes an opcode for calling a native CDP1802 subroutine, **0x0nnn** where **nnn** is the entry point.  Real CHIP-8 programs could and did use this functionality.
* The clear screen and (interpreted) subroutine return opcodes are just special cases of the native subroutine call opcode that call subroutines at well-known addresses in the interpreter’s code (0x0E0 for clear screen and 0x0EE for subroutine return).  This is very much a leaky implementation detail.
* CHIP-8 programs implicitly *do* care about the interpreted instruction throughput and latency.  It needs to be fast enough relative to the 60Hz timers to ensure that logic isn’t broken by code executing too slowly, and the software will be written to be fast enough with a given platform and interpreter.  This is before you get into the realm of software that uses throughput of a given platform to determine the game speed (hello Space Invaders and Cave shooters).

Implementation details leaked in other interpreters, too:
* CHIP-8 programs for the ETI-660 start at address 0x600 rather than 0x200 due to the different memory layout.
* The Spacefight 2019! game will only run on the Commodore Amiga CHIP-8 interpreter because it depends on the **0xFx1E** instruction (add Vx to pointer register I) setting VF to range overflow status which no other CHIP-8 interpreter does.
* Conversely, other games (e.g. Animal Race) will not run on the Amiga CHIP-8 interpreter because they depend on VF being unaffected by the **0xFx1E** instruction.

MAME preserves technology history, which CHIP-8 was an important part of, being an accessible way to develop games for cheap, limited home computers from the mid ’70s to early ’80s.  The simplicity meant it was easy to develop an interpreter, it didn’t need a lot of expensive memory, and it didn’t even need a full-size keyboard.  These were significant advantages over BASIC on low-cost systems.  The names of the newsletters that published the CHIP-8 programs reflect the names of the systems that the CHIP-8 programs were designed to run on (e.g. VIPER for the COSMAC VIP and DREAMER for the Electronics Australia DREAM 6800).

CHIP-8 largely fell out of use after that until CHIP-48 was released for HP-48 graphing calculators in 1990, followed by SCHIP.  At this point, it was more or a curiosity than anything else, providing a easier way to write simple games than using SysRPL.  Interest in CHIP-8 as a simple introduction to writing a virtual machine or bytecode interpreter is largely a response to documentation published by David Winter, who also wrote CHIP-8/SCHIP interpreters for HP-48 and PCs.

CHIP-8 isn’t really part of *gaming* history, it’s part of *hobbyist computer* history.  You can only really understand and appreciate it in the context that lead to its development.  MAME emulates all the major low-cost computer platforms where CHIP-8 emerged, as well as the HP-48 calculators where it experienced a renaissance.

**Comment by cuavas** [comment]
Oh, and by the way, most of this is very well-known, and can be gleaned from the relevant Wikipedia page: https://en.wikipedia.org/wiki/CHIP-8

You can still read David Winter’s highly influential document: http://vanbeveren.byethost13.com/stuff/CHIP8.pdf
