### ISSUE TITLE
k056230.cpp: Interface is outdated

### ISSUE THREAD

**Issue by Hydreigon223** [mamedev/mame#9371]
The current interface only has support for a processor connected to interrupt 2 because at the time, only zr107 and gticlub were known to use this custom. Because there are other pieces of hardware, racinfrc in konamigx, plygonet and thunderh's I/O board, that wire this custom to a different interrupt level, it's currently impossible to hook this to these three.

Also plygonet is known to use 2k x 8-bit network ram while all others use 8k x 8-bit meaning shared ram hookup technically isn't correct. Is the ram somehow mirrored for all games but plygonet?

**Comment by angelosa** [comment]
https://github.com/mamedev/mame/blob/master/src/devices/machine/k056230.cpp#L15

Not sure what's your point here, also the games in question are flagged with `MACHINE_NODEVICE_LAN` already. 
And your "impossible" just mean adding a `devcb_write_line` public setter instead of passing the CPU object to the device constructor, something that imho don't need to be logged in the issue tracker since it's just the tip of the iceberg from what I can tell.

**Comment by cuavas** [comment]
There's no point opening issues like this against a stub device.
