### ISSUE TITLE
Request for new version

### ISSUE THREAD

**Issue by JerryDaga** [mamedev/mame#9479]
Good day.
I have a suggestion regarding your MAME Emulator please add the MIDI capability to control mapping, for example, E drum and E Piano (keyboard) also cheat support because the latest version does not support cheat compare to the older version.
Thanks :)

**Comment by angelosa** [comment]
1. “Request for new version” is not a brief description of what you’re describing in body

2. Body has two completely unrelated issues

3. Cheat is now a plugin system, you probably don’t have it enabled in the correlated config file.

4. MIDI & synth portion is a relatively recent addition that is known to need UI/UX discussion at some point in future. It’s likely more suited to a forum rather than here in the first place.

**Comment by JerryDaga** [comment]
So what can I do ??

**Comment by happppp** [comment]
midi stuff: you can wait for us to improve it. Or if you're a coder, you can contribute with Pull Requests.
cheats: works fine, you can ask somewhere else if you need help with how to set it up. For example: https://www.reddit.com/r/MAME/ Not here, github issues is not a user support forum.

**Comment by JerryDaga** [comment]
Ok, thanks.
