### ISSUE TITLE
SGI Indy garbled framebuffer output in Linux/MIPS

### ISSUE THREAD

**Issue by darkstar** [mamedev/mame#9667]
When booting the Debian 3.0 installer for Linux/MIPS on the indy_5015 driver (MAME 0.243), the Kernel output to the framebuffer is garbled (every character is mirrored vertically):
![image](https://user-images.githubusercontent.com/43795/166160559-f2546fcc-24a8-475c-9da9-5d9df8c93d70.png)

Also, SCSI devices are not detected properly as can be seen in the screenshot.

Otherwise it seems to boot and work fine, here is a video of it:

https://user-images.githubusercontent.com/43795/166160588-82f496bf-2b0b-4f23-b50a-775ba72883fd.mp4

The Debian 3.0r0.1 CD ROM image for MIPS can be downloaded from [here](https://s3.au.de:8082/md1-stuff/debian_3_0_r_0_1_sgi_mips.chd)

**Comment by MooglyGuy** [comment]
SCSI devices not functioning properly under MIPS Linux might be me or might be @tyfighter depending on whether the breakage is in the HPC-side hookup, or if it's in the WD33C93 device itself.

The upside-down text is totally on me, though, but I'm tempted to leave it as-is, because I find it hysterically funny.
