### ISSUE TITLE
src/mame/drivers/kingdrby.cpp, cowrace - causes MAME to watchdog-exit

### ISSUE THREAD

**Issue by MooglyGuy** [mamedev/mame#9787]
Over the past 2-3 evenings, I've been trying to track down an issue in `cowrace` over in the `kingdrby` driver because @Tafoid flagged it when testing some upcoming device_timer changes that I'm making. However, it turns out that it also hangs MAME and results in a watchdog exit in the current top-of-tree as well.

This issue did not occur in the release version of MAME 0.243, so I believe Github is the appropriate location for this issue filing.

**Comment by MooglyGuy** [comment]
The issue has been tracked to commit 44dae68dbb5cd5d9fbb56e919e7bb59644830d2c. As the commit itself involves notable improvements to the ZX Spectrum driver, and cowrace is already marked MACHINE_NOT_WORKING, this is a minor issue and can be handled via normal channels.

**Comment by Tafoid** [comment]
Keeping it on my test list of exceptions/unknowns found was completely my mistake.
The original regression is https://github.com/mamedev/mame/commit/44dae68dbb5cd5d9fbb56e919e7bb59644830d2c and I failed to post to GitHub regarding it.

**Comment by smf-** [comment]
The 6845 has it's own vblank callback & before the screens vblank has
fired it calls screen().reset_origin()

void screen_device::reset_origin(int beamy, int beamx)

{

....

     // if we are resetting relative to (visarea.bottom() + 1, 0) ==
VBLANK start,
     // call the VBLANK start timer now; otherwise, adjust it for the future
     if (beamy == ((m_visarea.bottom() + 1) % m_height) && beamx == 0)
         vblank_begin();
     else
m_vblank_begin_timer->adjust(time_until_vblank_start());

As reset_origin() assumes you are telling when vblank ends, the next
vblank won't start for another frame & this code gets called again
before it ever fires so it gets pushed forward further and further.

As we hook all the OSD code off the primary screen's vblank then mame
appears to be locked up, though in reality mame is happily executing
it's infinite frame.

I'm not sure what in the z80 changes triggered this. But I can't work
out whether what the 6845 is doing is in any way correct either as it's
vblank and screen_device vblank don't appear to be in sync..

**Comment by holub** [comment]
I was able to narrowed down to commit which caused regression: 6f95e24708e0b40. In particular it was the changes in wm16().
```
inline void z80_device::wm16(uint16_t addr, PAIR &r) {
 	m_icount_executing -= MTM;
-	wm(addr, r.b.l);
-	m_icount_executing += MTM;
 	wm(addr+1, r.b.h);
+	m_icount_executing += MTM;
+	wm(addr, r.b.l);
}
```
This version is incorrect and had couple more transformations after but I think the issue is identified. It's hard to restore similar state in master (at least to validate if cowrace can work) as now z80 has different versions/order of writes-16 for different operations based on: https://sinclair.wiki.zxnet.co.uk/wiki/Contended_memory#Instruction_breakdown

Still not clear why changing the order of write_byte() hangs M.A.M.E in cowrace.
Open to any suggestions...

**Comment by smf-** [comment]
The slave CPU rom is missing and the driver instead let the CPU run with a ROM containing 0xff. 

This caused the Z80 to repeatedly execute an RST 38h instruction & as location 0x38 also contained an RST 38h instruction, it kept writing the program counter to the stack from address 0xffff to 0x0000 and then looped back to 0xffff again.

The 6845 is memory mapped at location 7600/7601 and changing from

SP-=2; wm(SP, r.l); wm(SP+1, r.h);
to
SP--; wm(SP, r.h); SP--; wm(SP, r.l);

changed the order of writes to the 6845 and somehow affected it's behavior. Writes to the 6845 probably shouldn't be able to take down MAME in such a way.

I have worked round the issue by replacing the CPU ROM.
